inc/shaarli.css
index.php
tpl/daily.html

Fixes #26
The timestamp's position and style can be modified, of course :smiley:

daily: display link timestamps

---

COPYING

Fixed license info, reverted qr.js to GPL

---

index.php

* Fixes https://github.com/shaarli/Shaarli/issues/110
* Based on pull request https://github.com/shaarli/Shaarli/pull/112

redirect to previous search (if any) when deleting a link

---

index.php

This should fix the bug related to sending too many cookies. Moved the login check to be executed only once during a render. This has the added benefit of preventing an extremely rare race condition from occuring (Having the user logged in at the beginning of the render and then reaching the timeout condition while rendering. Yes, I tested it. The results were... interesting.)
PLEASE TEST. Although I have tried most cases (logging in/out, generating a token that's broken, setting the session timeout at timestamp 0), I'd rather be sure nothing is broken. Nothing should be though.
This is also Shaarli's first mobile PR, sent from a car :beer:

Prevent shaarli from sending thousands of cookies.

---

index.php
tpl/configure.html
tpl/install.html

* Add a check box at installation (checked by default)
* Add a check box in configuration page

shaarli/Shaarli#34: Make update check optional

---

index.php

* Add some filters to clean URLs 	
* cleanup: refactor annoying URL patterns in a single loop

Add URL cleaning filters + refactoring

---

index.php

Because it's easy, and it's working.
EDIT: also, it's in 0.9 milestone.

Fixes shaarli/Shaarli#46: allow 'javascript:' links sharing

---

tpl/linklist.html

add placeholder text for search fields, change button text to magnifying glass
Merging on Sunday, March 15 if no one disagrees.

better looking search fields

---

index.php

Should fix up what went wrong.

Display notes as absolute URLs

---

index.php

Fixes this bug : https://github.com/shaarli/Shaarli/issues/175

Fix missing permalink title page when logged in

---

index.php

Links are now properly hidden in daily/RSS/tags/picwall/etc.

Properly hide all links. Fixes #212

---

inc/shaarli.css
index.php
tpl/linklist.html

This PR adds autocomplete on search by tags field. It's case insensitive.

Add awesomplete to tag search shaarli/Shaarli#49

---

index.php

**Scenario:** `HIDE_PUBLIC_LINKS` is enabled, and user isn't logged in.
**Current solution:** Removing loaded links before building each view.
**PR solution:** Don't load the links in `linkdb` class.
This also fixes the issue shaarli/Shaarli#202.

Do not load links if they're hidden (also fix shaarli/Shaarli#202)

---

inc/shaarli.css
tpl/loginform.html

improved form login

---

inc/awesomplete.css
inc/shaarli.css

Need to merge
When merge my responsive fix with ArthurHoaro/search-tag-awesomplete  the mobile layout broke..

filter input search responsive fixed (mobile) need to merge ASAP

---

index.php

Page title if there is a single link

---

application/LinkDB.php
index.php
tpl/daily.html
tpl/dailyrss.html
tpl/editlink.html
tpl/import.html
tpl/linklist.html
tpl/loginform.html
tpl/page.footer.html
tpl/page.header.html
tpl/picwall.html
tpl/tagcloud.html

I reviewed character escaping everywhere with the following ideas:
* use a single common function to escape user data: `escape` using `htmlspecialchars`.
* sanitize fields in `index.php` after reading them from datastore and before sending them to templates.
It means no escaping function in Twig templates.
2 reasons:
* it reduces risks of security issue for future user made templates
* more readable templates
* sanitize user configuration fields after loading them.
Please review it carefully since it touches a lot of code.

Working on shaarli/Shaarli#224

---

application/LinkDB.php
tests/LinkDBTest.php

Fixes #200
Let me know if you want to change anything in the description.

Change fresh install default link

---

index.php

The bug was occuring only if we tried to access to the first day.

Fixes #260: previous/next day links in daily

---

application/LinkDB.php
application/Utils.php
index.php
tests/LinkDBTest.php
tests/UtilsTest.php

Adds a `checkDateFormat()` function that could be useful for date ranges in #246

LinkDB::filterDay(): check input date format

---

application/Config.php
index.php
tests/ConfigTest.php

options.php is not supported anymore, but its content will be automatically saved into config.php
Fixes shaarli/Shaarli#41
*TODO*: update [documentation](https://github.com/shaarli/Shaarli/wiki#configuration).

All settings are now stored in config.php

---

index.php
tpl/dailyrss.html

Allow custom date format and title in templates.
Also a bit of code style review.
Fixes #182

Include the whole <item> in Daily RSS template

---

index.php
tpl/editlink.html

* Prevent duplicate client side with awesomplete
* Prevent duplicate server side (save_edit processing)
Fixes #261

Avoid tag duplicates

---

application/Utils.php
index.php
tests/UtilsTest.php

* search tag
* delete tag
* pagination
* display privates only
* delete link
Move location generation to Utils.php + unit tests.
Fixes #256
@fturco: Since I can't reproduce your issue without hard coding values, please test this PR carefully.

Prevent redirection loop everytime we rely on HTTP_REFERER

---

.travis.yml

Travis documentation:
- http://docs.travis-ci.com/user/migrating-from-legacy/
- http://docs.travis-ci.com/user/workers/container-based-infrastructure/
- http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
For more information about Linux containers:
- underlying kernel API: [cgroups](https://www.kernel.org/doc/Documentation/cgroups/cgroups.txt)
- Fedora's [Resource Management Guide](http://docs.fedoraproject.org/en-US/Fedora/17/html-single/Resource_Management_Guide/index.html#sec-How_Control_Groups_Are_Organized)
- implementations:
- https://linuxcontainers.org/
- http://openvz.org/Main_Page
- https://www.docker.com/

Travis: use the container-based infrastructure

---

tpl/picwall.html

Black thumbnails on picture wall after upgrade #293

[fix]  #293 - Black thumbnails on picture wall after upgrade

---

application/TimeZone.php
index.php
tests/TimeZoneTest.php

Installation: default to the server's timezone

---

index.php

- add a use case for edit_link in logged out part.
- *really* prevent loops on login screen.

Fixes #299: prevent 404 on '?edit_link' while logged out

---

.gitignore
application/Url.php
index.php
tests/UrlTest.php

Reported in https://github.com/shaarli/Shaarli/pull/141#issuecomment-77268039

clean utm_term url parameter

---

application/LinkDB.php
application/Url.php
index.php
tests/Url/CleanupUrlTest.php
tests/Url/GetUrlSchemeTest.php
tests/Url/UnparseUrlTest.php
tests/Url/UrlTest.php

I just move the fix #325 to fix the GetLinkFromUrl method.
It would avoid in the future that somebody is calling this method with an Url object instead of a string.
I also added a unit test to ensure that GetLinkFromUrl accept a Url object (and avoid further regression).

#325 small enhancement to fix the GetLinkFromUrl method

---

plugins/addlink_toolbar/addlink_toolbar.css
plugins/addlink_toolbar/addlink_toolbar.html
plugins/addlink_toolbar/addlink_toolbar.php
tests/plugins/PluginAddlinkTest.php

Add a field in linklist page to paste a new link.
Displayed in fields toolbar.

PLUGIN: addlink_toolbar

---

application/Router.php
index.php
tpl/includes.html
tpl/opensearch.html

* add a new page in Router: do=opensearch which displays the opensearch plugin
* using base64 compressed image to avoid issue encountered with HTTPS

Fixes #176 - Add opensearch functionality

---

inc/awesomplete-multiple-tags.js
tpl/editlink.html
tpl/linklist.html

* Using the same code (and workaround) as in editlink.html
EDIT: and a bit of HTML indentation.

Fixes #360 - Auto-complete more than one tag in tag filter field

---

application/ApplicationUtils.php
application/Utils.php
index.php
tests/ApplicationUtilsTest.php
tests/UtilsTest.php

application: move checkPHPVersion from Utils to ApplicationUtils

---

application/LinkDB.php
application/Utils.php
index.php
plugins/qrcode/qrcode.php
tests/LinkDBTest.php
tests/UtilsTest.php
tests/plugins/PlugQrcodeTest.php
tpl/daily.html
tpl/linklist.html
tpl/picwall.html

Fixes #328
* WARNING - template edit - new variable available : "real_url"
Contains the final real url (redirected or any other change on original URL)
* Doesn't affect RSS feeds.

URL encode links when a redirector is set

---

application/ApplicationUtils.php
index.php

Regression introduced in #394, thanks @ArthurHoaro for spotting it ;-)

fix: assign template variables to empty values so they can be evaluated

---

index.php

only set the title on permalink.

Temporary fix for head titles

---

tpl/tools.html

Minimal indent of tools.html

---

application/Router.php
index.php
plugins/demo_plugin/demo_plugin.php

* new entry in the Router for daily page.
* add an always displayed button in demo_plugin
#402

Fixes #402: build the daily page through renderPage()

---

plugins/demo_plugin/custom_demo.css
plugins/demo_plugin/demo_plugin.php
tpl/page.footer.html

Allow free elements at the end of the page.
Fixes #404 - issue not found.

Adding a new placeholder in render_footer hook.

---

.gitattributes
docker/.htaccess
docker/development/Dockerfile
docker/development/IMAGE.md
docker/development/nginx.conf
docker/development/supervised.conf
docker/production/Dockerfile
docker/production/IMAGE.md
docker/production/nginx.conf
docker/production/stable/Dockerfile
docker/production/stable/IMAGE.md
docker/production/stable/nginx.conf
docker/production/stable/supervised.conf
docker/production/supervised.conf

Docker: move Dockerfiles to the main repository

---

application/Url.php
plugins/wallabag/README.md
plugins/wallabag/WallabagInstance.php
plugins/wallabag/config.php.dist
plugins/wallabag/wallabag.html
plugins/wallabag/wallabag.php
tests/Url/UrlTest.php
tests/plugins/PluginWallabagTest.php
tests/plugins/WallabagInstanceTest.php

* Fixes a bug where URL weren't properly encoded.
* Adds Wallabag V2 support.
* Adds a URL function to handle trailing slash.
* UT.
* README updated.

Wallabag plugin improvement

---

index.php

Also adds a validation where renaming with 'fromtag' specified and empty 'totag'.
It was causing a 404, now it just re-render the form.

Fixes #428: validate buttons presence instead of value

---

application/Utils.php
index.php
tests/UtilsTest.php

Relates to #436
Modifications:
- inject dependencies to global variables ($_SERVER, $GLOBALS)
- apply coding conventions
- add test coverage

Logging: move logm() from index.php to application/Utils.php

---

inc/shaarli.css
index.php
tpl/404.html

Solve #430 
Do you think creating a method to generate a 404 template in the class pageBuilder is a good solution ?

Create 404 template

---

tpl/404.html

https://github.com/shaarli/Shaarli/commit/db36b8812d30d2a1dcb1a5a0544893ee863f45dd#commitcomment-15605040

remove whitespace

---

application/LinkFilter.php
tests/LinkFilterTest.php

Implemented a little more sophisticated searching (squashed)

---

index.php

pluginsadmin -> Router::$PAGE_PLUGINSADMIN

Fixes typo in plugin admin redirection URL

---

application/LinkFilter.php
tests/LinkDBTest.php
tests/LinkFilterTest.php
tests/utils/ReferenceLinkDB.php

Handles those searches
> "exact search" term other term -notthis "very exact" stuff -notagain
Fixes #454 and fixes #358 (combined with #446).

Improved search: combine AND, exact terms and exclude search.

---

inc/shaarli.css
tpl/pluginsadmin.html

Fixes #494: inputs & labels with plugin name

---

inc/shaarli.css
plugins/archiveorg/archiveorg.html
plugins/qrcode/qrcode.html
plugins/readityourself/readityourself.html
plugins/wallabag/wallabag.html

Set in Shaarli's CSS instead.
#411

Fixes #411: remove hardcoded plugin icon size

---

index.php

Fixes #503: check that HTTP_ACCEPT_LANGUAGE is set before calling autolocale

---

application/LinkUtils.php
tests/LinkUtilsTest.php

Fixes #512: retrieving title didn't match the first closing tag

---

index.php

Use generateLocation to set the redirection in login (and don't escape the url)

---

application/Url.php
tests/Url/UrlTest.php

Fixes #366
Closes #380
Regarding @virtualtam comment back then:
> this method should be static
I don't see any particular reason to do so since other clean method aren't static.

Refactor and rebase #380: Firefox reader view links

---

plugins/markdown/markdown.php

Process feeds content with Markdown

---

inc/awesomplete-multiple-tags.js

Renames Awesomeplete dollar variable to avoid conflicts with jQuery

---

application/HttpUtils.php
application/Router.php
application/Utils.php
index.php

Apparently PHP doesn't care, but it was bothering me.

Fix startsWith and endsWith case

---

index.php
tpl/loginform.html

Users are more likely going to mistype their password. This PR keeps the username in the form when the authentication has failed.

Prefill the login field when the authentication has failed

---

README.md

README: add link to the upgrade and migration wiki page

---

composer.json

See https://getcomposer.org/doc/04-schema.md

Update composer metadata

---

application/LinkDB.php
tests/LinkDBTest.php
tests/utils/ReferenceLinkDB.php

Correct PR #573 to work properly with hidden tags, and add ReferenceLinkDB UT.
Fixes #571 - Closes #573

Better whitespace handling in tags

---

application/Updater.php
tests/Updater/UpdaterTest.php

* Actually run it
* unit tests
Fixes #611

Fix update method escapeUnescapedConfig

---

.gitattributes

Fix: keep composer.json in release archives

---

docker/production/stable/Dockerfile

Relates to https://github.com/shaarli/Shaarli/pull/612
Relates to https://github.com/shaarli/Shaarli/pull/624
Relates to https://github.com/shaarli/Shaarli/pull/633
See https://github.com/shaarli/Shaarli/wiki/Server-requirements
Modifications:
- [prod][stable] refactor Dockerfile
- [prod][stable] set $TERM=dumb to avoid debconf-related issues
- [prod][stable] install ca-certificates
- [prod][stable] cleanup APT cache after installing packages
- [prod][stable] use Composer to resolve PHP dependencies

Docker: update dependencies, introduce Composer (stable branch)

---

docker/production/stable/Dockerfile

Add a missing backslash in stable Dockerfile version

---

plugins/archiveorg/archiveorg.php
tests/plugins/PluginArchiveorgTest.php

Archive.org plugin: do not propose archival of private notes

---

application/FeedBuilder.php
tests/FeedBuilderTest.php

Fixes https://github.com/shaarli/Shaarli/issues/629
Closes https://github.com/shaarli/Shaarli/pull/630
Note: you might need to empty the "pagecache" directory for the
fix to be taken into account
ping @Aldarone

Fix: return the proper value for the "self" feed attribute

---

.travis.yml
CHANGELOG.md

See:
- https://docs.travis-ci.com/user/caching/
- https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/

Travis: enable Composer cache

---

CHANGELOG.md
application/FeedBuilder.php
tests/FeedBuilderTest.php

Make the hashtag link absolute in feeds to work properly in RSS syndication tools.

Fix hashtag links in Feeds

---

plugins/piwik/piwik.meta
plugins/piwik/piwik.php

Add ability to user to link Shaarli instance to a Piwik installation.

Piwik Plugin

---

plugins/archiveorg/archiveorg.html
plugins/qrcode/qrcode.html
plugins/readityourself/readityourself.html
plugins/wallabag/wallabag.html

Add an alt attribute to images

Plugins W3C compliance

---

tpl/includes.html

Add a meta tag that tells the browser not to send the referrer header.

add meta tag to block sending the referrer

---

tpl/editlink.html

Also changes all tabs to 4 spaces.
Fixes #695.

Show page title when sharing via Firefox Social.

---

inc/shaarli.css
plugins/markdown/README.md
plugins/markdown/markdown.meta
tpl/pluginsadmin.html

Describe markdown HTML rendering and display a warning

---

CHANGELOG.md

It's early, feel free to correct my potato English. 😸

Add latest merged changes to the CHANGELOG

---

.travis.yml
tpl/loginform.html

Also added PHP 7.1 to travis tests.
Fixes #711 - ping @robertharm if you can give it a try.

Fixes can login function call in loginform.html

---

tpl/feed.atom.html
tpl/feed.rss.html

Add opensearch to RSS and ATOM feeds

---

index.php

Unlucky copy/paste made in #666

Fix fatal error during the install

---

application/Url.php
tests/Url/CleanupUrlTest.php

Closes https://github.com/shaarli/Shaarli/issues/735
I also took the opportunity to split test assertions into several test cases :)

URL cleanup: add 'campaign_' to the annoying parameters

---

docker/development/nginx.conf
docker/production/nginx.conf
docker/production/stable/nginx.conf

Closes https://github.com/shaarli/Shaarli/issues/668
Changed:
- let nginx rewrite API URLs

API+Docker: enable nginx URL rewriting

---

application/HttpUtils.php
application/LinkUtils.php
application/Updater.php
index.php

Note: I deliberately left an "unsafe" boolean comparison in thumbnail functions to avoid a conflict with #687 :)

Cleanup: use safe boolean comparisons

---

application/Updater.php
tpl/default/includes.html

Reasons:
- easier to update (just keep data folder)
- no git conflicts

Move user.css to data folder

---

tpl/default/css/shaarli.css
tpl/default/editlink.html

This one was forgotten in #682 
Fixes #749

Fix delete button in editlink

---

application/api/ApiUtils.php
application/api/controllers/Links.php
index.php
tests/api/ApiUtilsTest.php
tests/api/controllers/LinksTest.php

See http://shaarli.github.io/api-documentation/#links-links-collection-get

REST API: implement getLinks service

---

index.php

Relates to https://github.com/shaarli/Shaarli/issues/599
Relates to db6b09b69ee265a7d775924fcff9c61aaaabf1cb

Bump expected minimal PHP version to 5.5

---

index.php

Prevent tag duplicate when renaming

---

plugins/addlink_toolbar/addlink_toolbar.php
tests/plugins/PluginAddlinkTest.php

Remove CSS call for addlink toolbar plugin

---

index.php

Prevent warning if HTTP_REFERER isn't set

---

index.php

Fix redirection after link deletion

---

index.php
tpl/default/css/shaarli.css
tpl/default/editlink.html

+ fix changetag CSS alignement
relates to #756

Stay on the changetag page after tag deletion

---

application/LinkDB.php
application/LinkFilter.php
application/api/controllers/Links.php
index.php
tests/LinkFilterTest.php

No update regarding the UI or the API for now
Fixes #758

Update LinkFilter to be able to filter only public links

---

application/api/controllers/Links.php
application/api/exceptions/ApiLinkNotFoundException.php
index.php
tests/api/controllers/GetLinkIdTest.php
tests/api/controllers/GetLinksTest.php

See http://shaarli.github.io/api-documentation/#links-link-get

REST API: implements getLink by ID service

---

tpl/default/editlink.html
tpl/default/js/shaarli.js

It's a common shortcut (Github, Reddit, SO, etc) which I found annoying not to have it in Shaarli.

Submit editlink textarea using CTRL+Enter shortcut

---

application/config/ConfigPlugin.php
application/config/exception/PluginConfigOrderException.php
composer.json
index.php
tests/config/ConfigPluginTest.php
tpl/default/css/shaarli.css
tpl/default/linklist.html

Fixes #433 
Also fix a namespace issue (more incoming).
Rendering (github is compressing jpg a bit too much):

Display private only filter as search criteria

---

tpl/default/linklist.html
tpl/default/page.header.html

data-autofirst automatically selects the first item of the list of choice automatically. You just have to press enter to use it.

Fixes #657: use data-autofirst parameter for awesomeplete

---

README.md

Note: it works fine here, but it may take a few hours for the DNS to work properly.

Shaarli demo moved to shaarli.org

---

COPYING
inc/awesomplete-multiple-tags.js
inc/plugin_admin.js
plugins/piwik/piwik.html
plugins/playvideos/youtube_playlist.js
plugins/qrcode/shaarli-qrcode.js
tpl/default/configure.html
tpl/default/editlink.html
tpl/default/install.html
tpl/default/js/shaarli.js
tpl/default/loginform.html
tpl/default/picwall.html
tpl/default/pluginsadmin.html
tpl/default/tools.html

Fixes #33 (wow!)
Relates to #395

Remove inline JS and add LibreJS headers in JS files

---

tpl/default/configure.html
tpl/default/css/shaarli.css

Theme: Vertical align theme select in configure

---

CHANGELOG.md
tpl/default/page.footer.html

Theme: display shaarli version in the footer when logged in

---

application/PageBuilder.php
application/Updater.php
application/config/ConfigManager.php
tests/Updater/UpdaterTest.php
tpl/default/page.header.html

RSS feed is still available with the  setting set to false

Fixes #304: use atom feed as default

---

README.md

Closes https://github.com/shaarli/Shaarli/issues/823
Preview at https://github.com/virtualtam/Shaarli/tree/readme/badges
TODO:

README: use explicit version badges

---

index.php

Fixes a bug preventing to edit link with ID 0

---

index.php
tpl/default/configure.html
tpl/default/install.html
tpl/vintage/configure.html

Also use the same variable name across template files

Add API setting in the new theme during the installation

---

index.php

Tags parameter for redirects

---

application/Utils.php
index.php
tests/languages/de/UtilsDeTest.php
tests/languages/en/UtilsEnTest.php
tests/languages/fr/UtilsFrTest.php
tpl/default/daily.html

Note that the existing theme variable `day` has been preserved.

Theme: use format_date function for daily date

---

index.php

Display daily date in the page title (browser title)

---

application/api/ApiUtils.php
application/api/controllers/ApiController.php
application/api/controllers/Links.php
index.php
tests/api/controllers/PostLinkTest.php
tests/utils/ReferenceLinkDB.php

See http://shaarli.github.io/api-documentation/#links-links-collection-post

REST API: implement POST link service

---

tpl/default/configure.html
tpl/vintage/configure.html
tpl/vintage/page.header.html

Rename title link label to home link and apply it in vintage theme

---

application/api/ApiUtils.php
application/api/controllers/Links.php
index.php
tests/api/ApiUtilsTest.php
tests/api/controllers/PutLinkTest.php

* Related to #609
* Documentation: http://shaarli.github.io/api-documentation/#links-link-put
~~And this is the last one!~~ No, actually it's not.

REST API: implement PUT method

---

application/api/controllers/Links.php
composer.lock
index.php
tests/api/controllers/DeleteLinkTest.php

Based on #840
See http://shaarli.github.io/api-documentation/#links-link-delete

API: add DELETE endpoint

---

application/api/controllers/History.php
index.php
tests/api/controllers/HistoryTest.php
tests/utils/ReferenceHistory.php

See http://shaarli.github.io/api-documentation/#links-history-get

API: Get History endpoint

---

application/Updater.php
tests/Updater/UpdaterTest.php

Use the new 'default' theme... as default

---

index.php
tpl/default/css/shaarli.css
tpl/default/js/shaarli.js
tpl/default/linklist.html
tpl/default/page.header.html

* Add a checkboxes in linklist which display a sub-header containing action buttons
* Strongly rely on JS
* ~~Requires a modern browser (ES6 syntax support)~~
* Checkboxes are hidden if the browser is old or JS disabled
Fixes #644 
Relates to #572 (checkboxes and action buttons can be re-used)

Bulk deletion

---

tpl/default/tools.html
tpl/vintage/tools.html

Add Note bookmarklet #580

---

tpl/default/css/shaarli.css

Display visited links in grey

---

tpl/default/tools.html

to avoid having too large URL
Fixes #528

Selection is now limited to 2k characters using bookmarklets

---

index.php
tpl/default/css/shaarli.css
tpl/default/editlink.html

Also, alter the title on edition
Fixes #431

Add creation date when editing a link

---

application/HttpUtils.php
tests/HttpUtils/ServerUrlTest.php

alongside _PORT and _PROTO
Fixes #879

Respect HTTP_X_FORWARDED_HOST

---

tpl/default/page.footer.html

Remove merge conflict leftover

---

application/LinkDB.php
application/LinkFilter.php
application/PageBuilder.php
index.php
tests/LinkFilterTest.php
tpl/default/css/shaarli.css
tpl/default/linklist.html
tpl/default/linklist.paging.html
tpl/default/page.header.html

An instance displaying the effect of those changes can be tested here: https://chezsoi.org/shaarli

Using only one form in linklist.html - fix #885

---

application/LinkDB.php
index.php
tests/LinkDBTest.php

Fixes #886 
Also refactoring of CHANGETAG part in `index.php` to avoid duplicated code (separated commits).

Make sure that the tag exists before altering/removing it

---

doc/md/Community-&-Related-software.md
doc/md/REST-API.md

Relates to https://github.com/shaarli/Shaarli/issues/915

documentation: update 3rd-party resources

---

index.php

Sort tag cloud in alphabetical order

---

doc/md/Security.md
index.php

- removed references to legacy feature *magic quotes* (see 1st commit message)
- tiny code optimization: cookie expiration calculation (see 2nd commit message)
just some very small stuff I found, so I didn't open an issue (should I?)

small code cleanup

---

CHANGELOG.md
CONTRIBUTING.md
application/LinkDB.php
application/config/ConfigManager.php
composer.json
doc/md/Plugin-System.md
doc/md/Plugins.md
doc/md/index.md
index.php
plugins/playvideos/README.md

migrated Github wiki links to readthedocs

---

index.php

Generates a permalink URL if the URL is set to blank

---

index.php

- the previous code tried to use links from a previous day if there are no one for the current one
- the new code skips this part if there are no entries (i.e. days) at all
fixes #948

fixed daily links if there are no links

---

index.php
tpl/default/js/shaarli.js

fixes bulk deletion of links (see commit message)
fixes #949

fixed link deletion

---

Makefile
doc/md/Release-Shaarli.md

Fixes https://github.com/shaarli/Shaarli/issues/935

Documentation+Makefile: update AUTHORS generation

---

.travis.yml
tests/languages/de/UtilsDeTest.php
tests/languages/en/UtilsEnTest.php
tests/languages/fr/UtilsFrTest.php

Fixes https://github.com/shaarli/Shaarli/issues/970
Relates to https://github.com/shaarli/Shaarli/pull/912
See:
- https://docs.travis-ci.com/user/reference/trusty/
- https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Travis: switch to Ubuntu Trusty build environment

---

application/ApplicationUtils.php
application/FileUtils.php
application/ThemeUtils.php

See commit messages for details

Improve robustness for zlib and file operations

---

application/config/ConfigManager.php
doc/md/Shaarli-configuration.md
index.php

Took a shot at #963, this adds a config option for the default note title.

Allow setting of a default note title, see #963

---

doc/md/docker/docker-101.md
doc/md/index.md

Had to create a new pull request after force-push for #982 , didn't seem to reopen.
Remade commit with changes this time at requested space in index document. 
Also added a commit updating docker-101 with a bit on beyond pulling the image: creating, access and cleanup.
Hope all the syntax works and is in the right place.

Docker quickstart

---

index.php
tpl/default/tag.cloud.html

Vulnerability introduced by 6ccd0b218fbd34de750f55b78f3dc43bb3d9fa8e - released with Shaarli v0.9.1.
#986

Fix security issue reported by @chb9 

---

doc/md/Upgrade-and-migration.md

Good morning,
The ascii maze in https://shaarli.readthedocs.io/en/master/Shaarli%20configuration is nice, but the correct page is nicer ;)
Cheers,
Daniel

Fix link in Upgrade-and-migration.md

---

.editorconfig
data/.htaccess

Relates to #872
Relates to #993

Fix: enable access to data/user.css (Apache 2.2 & 2.4)

---

doc/md/docker/reverse-proxy-configuration.md

Closes https://github.com/shaarli/Shaarli/issues/888
---
This is a first take, YMMV depending on your server and networking setup. Feel free to suggest/submit improvements!
Thanks @thewilli and @bvberkum for providing examples :)

Documentation: add reverse proxy examples for Docker images

---

application/LinkDB.php
application/Updater.php
tests/LinkFilterTest.php
tests/utils/ReferenceLinkDB.php

Performances: reorder links when they're written instead of read

---

tpl/default/css/shaarli.css
tpl/default/js/shaarli.js
tpl/default/linklist.html

* Reduce multiple margins (markdown, space between block, etc.)
* Move thumbnails to the right in the same line as the title
* Move edit button as floating to the left
* Move fold/collapse and checkbox buttons as floating to the right
* Add a bunch of HTML ID in the linklist template
Relates to #877

Theme improvements: move thumbnails to the right and reduce margins overall

---

application/FeedBuilder.php
application/LinkUtils.php
index.php
tests/LinkUtilsTest.php

Don't URL encode description links if parameter 'redirector.encode_url' is set to false

---

tpl/default/css/shaarli.css
tpl/default/tag.cloud.html
tpl/default/tag.list.html

Fix CSS class typo and display the link as a button
Fixes #999

Fix alignement and better clarity for 'List all links with those tags' button

---

inc/languages/fr/LC_MESSAGES/shaarli.po
tpl/default/pluginsadmin.html

* center information messages
* add a message if the enable plugins don't have any parameter
* hide the « save » button if there is no parameter
Fixes #931

Improve messages if there is no plugin or parameter available in the admin page

---

application/HttpUtils.php

1kB chunk size has caused me a lot of trouble with Travis which wasn't completing the download

Increase buffer size for cURL download

---

tpl/default/page.header.html

Add CSS classes and IDs in Shaarli's menu

---

CHANGELOG.md

Relates to https://github.com/shaarli/Shaarli/pull/1046

Reference CVE-2018-5249 in CHANGELOG

---

doc/md/Server-requirements.md

doc: Server Requirements: php-mbstring: add 'hosting providers'

---

doc/md/docker/shaarli-images.md

doc: add arm32v7 docker build documentation

---

doc/md/Backup,-restore,-import-and-export.md

doc: import: add link to derefind conversion tool

---

.travis.yml
application/Url.php
composer.json
composer.lock
tests/api/controllers/PostLinkTest.php

PHP 7.2 is currently in Release Candidate.

Drop PHP 5.5 compatibility and run Travis UT against PHP 7.2

---

index.php
plugins/demo_plugin/demo_plugin.php
plugins/markdown/markdown.php
tests/plugins/PluginMarkdownTest.php

WARNING: this PR breaks backward compatibility for plugins that use the render daily hook.

Executes daily hooks before creating columns.

---

.htaccess

See:
- https://en.internetwache.org/dont-publicly-expose-git-or-how-we-downloaded-your-websites-sourcecode-an-analysis-of-alexas-1m-28-07-2015/
- https://stackoverflow.com/questions/2530372/how-do-i-disable-directory-browsing
- https://httpd.apache.org/docs/current/mod/mod_rewrite.html

htaccess: prevent accessing resources not managed by SCM

---

doc/md/Directory-structure.md
doc/md/Plugins.md
doc/md/Troubleshooting.md
doc/md/Upgrade-and-migration.md

Closes https://github.com/shaarli/Shaarli/issues/1082

Documentation: cleanup, update references to config(.json)?.php

---

application/config/ConfigManager.php
inc/languages/fr/LC_MESSAGES/shaarli.po
index.php

Also fixed a few French translation issues
Fixes #954 
As mentioned in the issues, the search result title is:
* `Search: keyword1 keyword2 [tag1] [tag2] - Shaarli's title`
* `Search: keyword1 keyword2 - Shaarli's title`
* `Search: [tag1] [tag2] - Shaarli's title`
* `tag1 tag2 - Tag cloud - Shaarli's title`
* `tag1 tag2 - Tag list - Shaarli's title`

Use a specific page title in all pages

---

application/NetscapeBookmarkUtils.php
tests/NetscapeBookmarkUtils/BookmarkImportTest.php
tests/NetscapeBookmarkUtils/input/lowercase_doctype.htm

Ignore the case while checking DOCTYPE during the file import

---

application/FileUtils.php
application/LinkFilter.php
application/NetscapeBookmarkUtils.php
application/Url.php
application/api/controllers/History.php
application/api/controllers/Links.php
index.php
tests/plugins/test/test.php

See https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

PSR: use elseif instead of else if

---

application/Updater.php
index.php
tests/Updater/UpdaterTest.php

Make max download size and timeout configurable

---

index.php

It has been removed from the web page.
Fixes #1099

Fix warning when trying to save redictor setting from the configure page

---

tpl/vintage/loginform.html

Introduced by https://github.com/shaarli/Shaarli/pull/1008

fix: IP ban check for the Vintage theme

---

tpl/default/includes.html
tpl/vintage/includes.html

small change, so that you can also easily change styles for e.g. markdown plugin in your user.css

load user css at last, after plugin css to enable changing plugin styles

---

application/LinkUtils.php
index.php

* Fix parameter order which was preventing max_dl parameter to work properly
* Support redirection in cURL download callback

Title retrieval fixes

---

plugins/markdown/markdown.php
tests/plugins/PluginMarkdownTest.php

Fix feed permalink rendering with markdown escape set to true

---

index.php

$loginManager was out of scope
related to #1086

Fixes an error during the install

---

doc/md/docker/reverse-proxy-configuration.md

Include ProxyPreserveHost directive in Apache's proxy doc

---

Dockerfile

Major change:
- PHP 7.2
Changelog:
- https://www.alpinelinux.org/posts/Alpine-3.8.0-released.html

Bump the base Docker image to alpine:3.8

---

.htaccess

Use version condition in the root .htaccess

---

assets/default/js/base.js
index.php

Fix a JS bug preventing AJAX tag deletion to work

---

index.php

Add CORS headers to REST API responses

---

tpl/default/daily.html
tpl/default/linklist.html
tpl/default/picwall.html
tpl/vintage/daily.html
tpl/vintage/linklist.html
tpl/vintage/picwall.html

This is quite a massive bug for a single character in HTML templates... :frowning:

Fix a bug making thumbnail to request the current page

---

assets/default/js/base.js
assets/default/scss/shaarli.scss
tpl/default/linklist.html
tpl/default/linklist.paging.html

Add a button to toggle all checkboxes of displayed links

---

doc/md/index.md

- simplify/organize feature list and contributing section
- move bug reporting/contact information to Contributing section
- unclutter
Ref https://github.com/shaarli/Shaarli/issues/1148#issuecomment-397871451 and https://github.com/shaarli/Shaarli/issues/598

doc: refactor documentation homepage

---

composer.json
composer.lock

Relates to https://github.com/shaarli/Shaarli/issues/1227

Composer: bump netscape-bookmark-parser to 2.1

---

doc/md/Community-&-Related-software.md

Author's repo moved to Framagit

Dead link on dead link detector tool

---

doc/md/Server-configuration.md

Ref https://github.com/shaarli/Shaarli/issues/1249

doc: update PHP compatibility table

---

tpl/default/includes.html
tpl/vintage/includes.html

Fixes https://github.com/shaarli/Shaarli/issues/1250
Relates to https://github.com/shaarli/Shaarli/issues/1242

fix: ensure HTML tags are stripped from OpenGraph description

---

doc/md/Shaarli-configuration.md

Fixes warnings from https://travis-ci.org/shaarli/Shaarli/jobs/486928133

doc: fix invalid links

---

application/Thumbnailer.php

It was not disabling anything.

Fix thumbnails disabling if PHP GD is not installed

---

application/api/ApiMiddleware.php
application/bookmark/LinkDB.php
application/bookmark/LinkUtils.php
application/config/ConfigManager.php
application/feed/FeedBuilder.php
application/updater/Updater.php
doc/md/Shaarli-configuration.md
index.php
tests/bookmark/LinkDBTest.php
tests/bookmark/LinkUtilsTest.php
tests/plugins/PluginMarkdownTest.php
tests/updater/UpdaterTest.php

Remove the redirector setting

---

application/api/ApiUtils.php
application/bookmark/LinkUtils.php
application/feed/FeedBuilder.php
application/netscape/NetscapeBookmarkUtils.php
index.php
tests/bookmark/LinkUtilsTest.php

Do not try to retrieve thumbnails for internal link

---

application/render/PageBuilder.php
index.php
tpl/default/404.html
tpl/default/addlink.html
tpl/default/changepassword.html
tpl/default/changetag.html
tpl/default/configure.html
tpl/default/daily.html
tpl/default/editlink.html
tpl/default/export.html
tpl/default/import.html
tpl/default/install.html
tpl/default/linklist.html
tpl/default/loginform.html
tpl/default/picwall.html
tpl/default/pluginsadmin.html
tpl/default/tag.cloud.html
tpl/default/tag.list.html
tpl/default/thumbnails.html
tpl/default/tools.html

The lang is based on the user defined one. If the language is automatic, no language will be specified.
Fixes #1216

Accessibility: specify the HTML lang attribute

---

tpl/default/linklist.html
tpl/default/linklist.paging.html
tpl/default/page.footer.html
tpl/default/page.header.html
tpl/default/tag.sort.html

1. Add the HTML5 tag footer and role contentinfo
2. Fix empty links with aria-label and hide icons from screenreaders

accessibility fixes

---

inc/languages/fr/LC_MESSAGES/shaarli.po

add "Select all" string and French translation

---

AUTHORS
CHANGELOG.md
README.md
doc/md/Download-and-Installation.md

Update README, CHANGELOG and AUTHORS for v0.10.4

---

application/Router.php
assets/default/js/base.js
index.php
tpl/default/page.header.html

Added 2 buttons when link checkboxes are checked to set them either public or private.
Related to #572 #1160

Bulk action: set visibility

---

assets/default/scss/shaarli.scss
tpl/default/linklist.html

Add sticky label, like private label, in linklist to make it more visible.

Display sticky label in linklist

---

tpl/default/linklist.paging.html

Bulk actions are not available on mobile view yet

Hide select all button on mobile view

---

package.json
yarn.lock

See https://github.com/sass/node-sass/issues/2625

Update node-sass to fix a vulnerability in node tar dependency

---

plugins/qrcode/qrcode.html
plugins/qrcode/qrcode.php

Remove QRCode link to an external service

---

.gitignore
inc/languages/fr/LC_MESSAGES/shaarli.po
index.php
tpl/default/daily.html
tpl/vintage/daily.html

Also mention if it's today or yesterday for clarity using `dayDesc`
variable
Fixes #1299

Daily - display the current day instead of the previous one

---

assets/default/scss/shaarli.scss

Responsive issue with delete button fix

---

AUTHORS
CHANGELOG.md

Signed-off-by: ArthurHoaro <arthur@hoa.ro>

Changelog and authors for v0.11 release

---

tpl/default/import.html
tpl/default/install.html
tpl/default/linklist.html
tpl/default/page.footer.html
tpl/default/page.header.html
tpl/default/picwall.html
tpl/default/tag.cloud.html
tpl/default/tag.list.html

- added main tag + role="main"
- delete useless tabindex
- aria-hidden <i>
- fix alt text (empty alt text needed)
- aria-label some inputs and buttons without name
And I also changed the linklist file with the idea I had in #1326.

a11y fixes

---

doc/md/Download-and-Installation.md

fixes https://github.com/shaarli/Shaarli/issues/1330

doc: fix broken markdown link

---

tpl/default/configure.html

fix link between label and checkbox (updateCheck)

little fix template

---

index.php

Bump PHP version check in index.php

---

tpl/default/includes.html
tpl/vintage/includes.html

Fix undefined thumbnail in OpenGraph headers

---

doc/md/Continuous-integration-tools.md

Fixes https://github.com/shaarli/Shaarli/issues/1335

doc: CI/dev tools: add paragraph about documentation/mkdocs

---

plugins/demo_plugin/demo_plugin.php

Fixes a few typos, restructures some sentences to make them easier to read.
Removed a few comments that were unnecessary.

Fix some typos and remove a few unnecessary comments in demo plugin

---

doc/md/index.md

Fixes https://github.com/shaarli/Shaarli/issues/598
Feel free to suggest different links/parameters to show in the main link list. I did with what I had, it shows a linklist fitered with `?searchtags=music`.
This may be related to https://github.com/shaarli/Shaarli/issues/1148, for example we could show a bit more complete markdown post, or feature some usage tricks.

Doc: add screenshots of all pages

---

.travis.yml
application/ApplicationUtils.php
application/api/ApiUtils.php
composer.json
composer.lock
tests/ApplicationUtilsTest.php
tests/PluginManagerTest.php
tests/api/ApiUtilsTest.php
tests/config/ConfigPhpTest.php
tests/feed/CachedPageTest.php
tests/updater/UpdaterTest.php

- Bump PHPUnit version
- Fix a few issues in UT related to PHPUnit upgrade
- Bump WebThumbnailer version (the new version dropped PHP 5.6/7.0 support)
Overall everything seems to be working properly.

Run Unit Tests against PHP 7.4

---

doc/md/Community-&-Related-software.md

Added a desktop app section
Fixes #1397

Ulauncher Extension

---

tpl/default/tag.cloud.html

Add autofocus on tag cloud filter input

---

application/bookmark/Bookmark.php
application/bookmark/BookmarkFileService.php
application/container/ContainerBuilder.php
application/front/controllers/DailyController.php
application/http/HttpUtils.php
application/legacy/LegacyLinkDB.php
application/render/PageCacheManager.php
index.php
tests/front/controller/DailyControllerTest.php
tests/http/HttpUtils/IndexUrlTest.php
tests/render/PageCacheManagerTest.php
tpl/default/daily.html
tpl/default/dailyrss.html
tpl/vintage/daily.html
tpl/vintage/dailyrss.html

The daily RSS template has been entirely rewritten to handle the whole feed through the template engine.

Process Daily RSS feed through Slim controller

---

application/front/controllers/SessionFilterController.php
application/front/controllers/ShaarliController.php
application/security/SessionManager.php
index.php
tests/front/controller/SessionFilterControllerTest.php
tests/front/controller/ShaarliControllerTest.php
tests/security/SessionManagerTest.php
tpl/default/linklist.paging.html
tpl/vintage/linklist.paging.html

Including:
- visibility
- links per page
- untagged only

Process session filters through Slim controllers

---

application/container/ContainerBuilder.php
application/container/ShaarliContainer.php
application/front/controller/admin/ExportController.php
application/netscape/NetscapeBookmarkUtils.php
doc/md/Translations.md
index.php
tests/front/controller/admin/ExportControllerTest.php
tests/netscape/BookmarkExportTest.php
tests/netscape/BookmarkImportTest.php
tpl/default/export.html
tpl/default/tools.html
tpl/vintage/export.html
tpl/vintage/tools.html

Also Use NetscapeBookmarkUtils object instance instead of static calls

Process bookmark exports through Slim controllers

---

application/security/SessionManager.php
index.php
tests/security/SessionManagerTest.php
tpl/default/linklist.paging.html

Also display the filter for visitors.
Fixes #1529

Fix broken route to filter not tagged bookmarks

---

application/bookmark/BookmarkArray.php
application/bookmark/BookmarkFileService.php
application/bookmark/BookmarkServiceInterface.php
application/feed/FeedBuilder.php
tests/feed/FeedBuilderTest.php

Fixed: Pinned bookmarks are displayed first in ATOM/RSS feeds

---

tpl/default/linklist.html

Default template: display pin button in mobile view

---

application/front/controller/admin/ShaarliAdminController.php
application/front/controller/visitor/ShaarliVisitorController.php
application/plugin/PluginManager.php
doc/md/Plugin-System.md

BookmarkServiceInterface related instance can now be accessed using `$data['_BOOKMARK_SERVICE_']`.
Related discussion: ilesinge/shaarli-related#7

Inject BookmarkServiceInterface in plugins data 

---

application/bookmark/BookmarkFileService.php
application/bookmark/BookmarkFilter.php
tests/bookmark/BookmarkFileServiceTest.php
tests/bookmark/BookmarkFilterTest.php

This filter (links by day) didn't apply any visibility parameter.
Fixes #1543

Fix visibility issue on daily page

---

application/bookmark/BookmarkInitializer.php
inc/languages/fr/LC_MESSAGES/shaarli.po
tests/bookmark/BookmarkFileServiceTest.php
tests/bookmark/BookmarkInitializerTest.php

Used @nodiscc suggestion in #1148 (slightly edited).
It provides a description of what Shaarli does, Markdown rendering demo, and a thumbnail link.
\+ translation
Fixes #1148
Regarding the discussion in #1148, even if it's not perfect, I think it's a great enhancement over what we currently have.
Here a screenshot of the page:

Improve default bookmarks after install

---

application/front/controller/admin/ManageShaareController.php

Fix redirection to referer after editing a link

---

doc/md/dev/Plugin-system.md
plugins/archiveorg/archiveorg.php
plugins/isso/isso.php
plugins/qrcode/qrcode.php
tests/plugins/PluginArchiveorgTest.php
tests/plugins/PluginIssoTest.php
tpl/vintage/linklist.paging.html

Also fix note check in archiveorg plugin, and regression on vintage template.
Documentation regarding relative path has been added.
Fixes #1548

Fix plugin base path in core plugins

---

application/front/controller/visitor/ShaarliVisitorController.php
tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php
tests/front/controller/admin/SessionFilterControllerTest.php
tests/front/controller/visitor/PublicSessionFilterControllerTest.php
tests/front/controller/visitor/ShaarliVisitorControllerTest.php

Fix invalid redirection using the path of an external domain

---

tpl/vintage/editlink.html

Fix undefined linkdate variable in vintage theme

---

assets/default/scss/shaarli.scss
tpl/default/tag.sort.html

This work alters the markup and CSS for the tag sort UI to match the button feel filters and links per page uses.
Fixes https://github.com/shaarli/Shaarli/issues/1437

 Issue #1437 - Make tag cloud/list views buttons more obvious

---

application/Utils.php
application/formatter/BookmarkFormatter.php
application/front/controller/admin/ManageShaareController.php
application/front/controller/admin/ManageTagController.php
application/front/controller/visitor/BookmarkListController.php
application/front/controller/visitor/TagCloudController.php
application/render/PageBuilder.php
assets/default/js/base.js
tpl/default/linklist.html
tpl/default/tag.cloud.html
tpl/default/tag.list.html

XSS vulnerabilities fixed in editlink, linklist, tag.cloud and tag.list.
They were introduced in v0.12.0-beta.
Also fixed tag search with special characters: urlencode function needs to be applied on raw data, before espaping, otherwise the rendered URL is wrong. Beforehand, Shaarli was only manipulating escaped data as soon as the datastore was read, which is not a very good practice.

Security: fix multiple XSS vulnerabilities + fix search tags with special chars

---

application/formatter/BookmarkMarkdownExtraFormatter.php
application/front/controller/admin/ConfigureController.php
composer.json
composer.lock
tests/formatter/BookmarkMarkdownExtraFormatterTest.php
tests/front/controller/admin/ConfigureControllerTest.php
tpl/default/includes.html

Library: [Parsedown Extra](https://github.com/erusev/parsedown-extra)
Also sort dependencies alphabetically.
Fixes #1169

Add Markdown Extra formatter

---

assets/default/js/base.js
inc/languages/fr/LC_MESSAGES/shaarli.po
tpl/default/changetag.html
tpl/default/page.footer.html

Improve Manage tags page

---

application/Utils.php
application/front/controller/visitor/ErrorController.php
index.php

Dislay an error if an exception occurs in the error handler

---

.docker/nginx.conf
doc/md/Server-configuration.md

Fix: nginx - add rule to disable url-rewriting for the docs

---

application/Utils.php
application/container/ContainerBuilder.php
application/container/ShaarliContainer.php
application/front/controller/visitor/LoginController.php
application/render/PageBuilder.php
application/security/BanManager.php
application/security/LoginManager.php
composer.json
composer.lock
index.php
tests/UtilsTest.php
tests/container/ContainerBuilderTest.php
tests/front/controller/visitor/LoginControllerTest.php
tests/security/BanManagerTest.php
tests/security/LoginManagerTest.php
tests/security/SessionManagerTest.php
tests/utils/FakeConfigManager.php

Use PSR-3 logger for login attempts 

---

application/History.php
application/Utils.php
application/bookmark/BookmarkFileService.php
application/bookmark/BookmarkServiceInterface.php
application/front/controller/admin/ServerController.php
application/front/controller/visitor/DailyController.php
application/front/controller/visitor/InstallController.php
application/helper/ApplicationUtils.php
application/helper/DailyPageHelper.php
application/helper/FileUtils.php
application/legacy/LegacyLinkDB.php
application/legacy/LegacyUpdater.php
application/render/PageBuilder.php
application/security/BanManager.php
composer.json
inc/languages/fr/LC_MESSAGES/shaarli.po
init.php
tests/bookmark/BookmarkFileServiceTest.php
tests/front/controller/visitor/DailyControllerTest.php
tests/helper/ApplicationUtilsTest.php
tests/helper/DailyPageHelperTest.php
tests/helper/FileUtilsTest.php
tests/security/BanManagerTest.php
tests/utils/FakeApplicationUtils.php
tests/utils/ReferenceHistory.php
tpl/default/daily.html
tpl/default/dailyrss.html

- Heavy refactoring of DailyController
- Add a banner like in tag cloud to display monthly and weekly links
- Translations: t() now supports variables with optional first letter
uppercase
Fixes #160

Feature: add weekly and monthly view/RSS feed for daily page 

---

application/render/PageBuilder.php
application/security/SessionManager.php

session_set_cookie_params does not return any value in PHP 7.1
Fixes #1603

Fix compatiliby issue on login with PHP 7.1

---

application/front/controller/admin/ShaarePublishController.php

Remove unnecessary escape of referer

---

plugins/wallabag/wallabag.php
tests/plugins/PluginWallabagTest.php

- hide the wallabag icon for logged out users
- set API V2 as default parameter
- fix URL encoding issue with special chars
Fixes #1147

Plugin wallabag: minor improvements

---

inc/languages/fr/LC_MESSAGES/shaarli.po

2 missing key + 1 wrong translation
Fixes  #1571

Fix French translation

---

application/bookmark/LinkUtils.php
application/formatter/BookmarkDefaultFormatter.php
doc/md/Shaarli-configuration.md
tests/formatter/BookmarkDefaultFormatterTest.php

+ update documentation
+ single parameter for both URL and hashtags
Fixes #1094

Default formatter: add a setting to disable auto-linkification

---

assets/default/js/base.js
inc/languages/fr/LC_MESSAGES/shaarli.po
tpl/default/changetag.html
tpl/default/page.footer.html

Regression introduced by #1596
Fixes #1623

Fix confirm popup before bookmark deletion

---

application/bookmark/BookmarkInitializer.php

Replace vimeo link in demo bookmarks due to IP ban on the demo instance

---

assets/vintage/css/shaarli.css
tpl/vintage/daily.html
tpl/vintage/editlink.html
tpl/vintage/page.header.html

* async metadata retrieval
* display global messages (errors, warnings and successes)
* routes in daily page

Fix a few compatibility issues with the vintage theme

---

application/Languages.php
inc/languages/ru/LC_MESSAGES/shaarli.po

All lines were translated to russian.

Add Russian translation

---

application/bookmark/BookmarkIO.php
application/front/controller/admin/ServerController.php
application/front/controller/visitor/InstallController.php
application/helper/ApplicationUtils.php
inc/languages/fr/LC_MESSAGES/shaarli.po

And display the error in server admin page
Fixes #1650

Fix: soft fail if the mutex is not working

---

Dockerfile

Apologize, I don't have the setup to run the unit tests and not worth that level of effort to me for this trivial of a change. Thus, feel free to ignore this PR. But I had already done the change and run it in local Docker, so I thought I'd put the PR out there just in case.

newer alpine (for newer PHP) and apk upgrade #1655

---

doc/md/REST-API.md

Fix for issue #1668 "Typo in line 76 of REST-API.md

Typo fix line 76 'Authentication' -> Authorization

---

application/bookmark/LinkUtils.php
tests/bookmark/LinkUtilsTest.php

Reference: https://stackoverflow.com/questions/8055727/negating-a-backreference-in-regular-expressions
Fixes #1656

Fix metadata extract regex (2)

---

plugins/default_colors/default_colors.php
tests/plugins/PluginDefaultColorsTest.php

Last update of this plugin remove the save_plugin_parameters hook.
Fixes #1657

Fix default_colors plugin: update CSS file on color change

---

application/front/controller/visitor/ShaarliVisitorController.php
tests/front/controller/visitor/ShaarliVisitorControllerTest.php
tpl/default/includes.html
tpl/vintage/includes.html

Make sure that header metadata associated with permalink is only used in linklist template.
Fixes #1686

Fix: error when using bulk shaare with a single URL 

---

tpl/default/editlink.batch.html
tpl/default/editlink.html

Use links loop ID to make ID unique and fix browser labels behaviour.
Fixes #1685

Fix: bulk add - use unique HTML ID

---

application/Utils.php
application/helper/ApplicationUtils.php

+ fix timezone issue with date formatting
Fixes #1692

curl usage: support HTTP/2 response code header

---

application/api/controllers/Links.php
application/api/controllers/Tags.php
application/bookmark/BookmarkFileService.php
application/bookmark/BookmarkServiceInterface.php
application/bookmark/SearchResult.php
application/feed/FeedBuilder.php
application/front/controller/admin/ManageTagController.php
application/front/controller/admin/ThumbnailsController.php
application/front/controller/visitor/BookmarkListController.php
application/front/controller/visitor/DailyController.php
application/front/controller/visitor/PictureWallController.php
application/netscape/NetscapeBookmarkUtils.php
application/updater/Updater.php
tests/bookmark/BookmarkFileServiceTest.php
tests/bookmark/SearchResultTest.php
tests/front/controller/admin/ManageTagControllerTest.php
tests/front/controller/admin/ThumbnailsControllerTest.php
tests/front/controller/visitor/BookmarkListControllerTest.php
tests/front/controller/visitor/DailyControllerTest.php
tests/front/controller/visitor/PictureWallControllerTest.php

Handle all search results through SearchResult object.
This is a required step toward implementing a BookmarkService based on SQL database.
Related to #953

Handle pagination through BookmarkService

---

composer.lock

Bump WebThumbnailer version to fix Instagram issue

---

doc/md/Server-configuration.md

Documentation: include all PHP extensions installed in our official Docker image

---

doc/md/Plugins.md

fixes https://github.com/shaarli/Shaarli/issues/1737

doc: plugins.md: fix link casing

---

doc/md/Troubleshooting.md

Based on https://github.com/shaarli/Shaarli/issues/1736, I propose a small extension of the documentation, to help people get on the right track when confronted with this `406 not acceptable` error.

Add '406 not acceptable' to the Troubleshooting section

---

doc/md/Troubleshooting.md

- left generic paragraph about this problem in place, since the problem may still be present on other sites
- closes https://github.com/shaarli/Shaarli/issues/1730

doc: bookmarklet is now working on github.com

---

doc/md/Server-configuration.md
doc/md/index.md

- fixes https://github.com/shaarli/Shaarli/issues/1677

doc: LDAP login support, update php requirements list

---

doc/md/Reverse-proxy.md
doc/md/Server-configuration.md

- fixes https://github.com/shaarli/Shaarli/issues/1679

doc: add notice about nginx location directive when shaarli is installed in a subdirectory

---

tpl/default/pluginsadmin.html
tpl/vintage/pluginsadmin.html

Intuitive checkbox for Enabled Plugins

---

README.md

It says HTTP 404 on travis-ci.com.

remove travis from README.md

---

doc/md/index.md

- fixes https://github.com/shaarli/Shaarli/issues/1774

doc: fix homepage title/icon rendering

---

doc/md/Shaarli-configuration.md

- Fixes https://github.com/shaarli/Shaarli/issues/1680

doc: add "formatter" setting to example.json.php, remove duplicate "general" key

---

application/api/exceptions/ApiException.php
application/bookmark/exception/DatastoreNotInitializedException.php
application/container/ShaarliContainer.php
application/front/exceptions/CantLoginException.php
application/front/exceptions/UnauthorizedException.php
tests/container/ShaarliTestContainer.php
tests/http/HttpUtils/GetIpAdressFromProxyTest.php
tests/http/HttpUtils/IsHttpsTest.php

- fixes https://github.com/shaarli/Shaarli/issues/1818

tests: phpcs: fix 'Opening brace must not be followed by a blank line' error

---

Dockerfile

- fixes https://github.com/shaarli/Shaarli/issues/1655

dockerfile: update base image to alpine 3.15

---

doc/md/Community-and-related-software.md
mkdocs.yml
tpl/default/tools.html

Rebuild and enhance. Stop hard-coded language in urls, broken Chrome extension url.
Unfortunately, I failed to pass variables to `t()` fun.

refine Community-and-related-software.md and tools page

---

tests/ThumbnailerTest.php

Quick and easy solution: try to reach GitLab instead.

Github Action: fix failing pipeline due to rate limit on githubassets.com

---

doc/md/Shaarli-configuration.md

doc: shaarli configuration: fixes/improvements to thumbnails settings documentation

---

application/Utils.php
application/api/controllers/HistoryController.php
application/bookmark/BookmarkArray.php
application/bookmark/LinkUtils.php
application/formatter/BookmarkDefaultFormatter.php
application/front/controller/admin/ThumbnailsController.php
application/helper/ApplicationUtils.php
application/http/Url.php
application/legacy/LegacyLinkDB.php

Resolve PHP 8.1 deprecations so we don't have our logs polluted with warnings.

 Resolve PHP 8.1 deprecations 

---

.github/workflows/ci.yml

- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures

tools/github actions: do not cancel all PHP jobs when a single one fails

---

tpl/default/install.html
tpl/default/loginform.html
tpl/default/page.header.html
tpl/vintage/install.html
tpl/vintage/loginform.html

Added `autocapitalize="off"` to the username input (regarding issue #434)

autocapitalize off for the username input

---

Dockerfile
Dockerfile.armhf

docker: install php8-ldap in Docker images

---

index.php
tpl/default/page.header.html

Not sure how I missed this one, probably a last minute change. :grimacing:

fix: bulk tag action - wrong controller name

---

doc/md/Usage.md

added in https://github.com/shaarli/Shaarli/pull/1587

doc: usage.md: add note about batch/bulk creation operation

---

doc/md/Community-and-related-software.md

Add mention to Shaarli Archiver

---

doc/md/Shaarli-configuration.md

fixes https://github.com/shaarli/Shaarli/issues/1906

doc: shaarli configuration: mention file:/// URIs

---

doc/md/Troubleshooting.md

- fixes https://github.com/shaarli/Shaarli/issues/1910
- fixes https://github.com/shaarli/Shaarli/issues/1854

doc: troubleshooting: add note to adjust proxy timeouts or PHP max execution time if encountering timeouts

---

tpl/vintage/linklist.paging.html

- fixes https://github.com/shaarli/Shaarli/issues/1946

template/vintage: fix typo in visibility selection link

---

.github/workflows/ci.yml
.github/workflows/docker-latest.yml
.github/workflows/docker-tags.yml
doc/md/Server-configuration.md

- fixes #1923 (updates to ubuntu-latest)
- fixes #1924 (updates to node16-dependend actions)
- fixes #1925 (python action needs python-version)

Github actions: update node

---

.github/workflows/ci.yml

- ref. https://github.com/shaarli/Shaarli/pull/1928

github actions: add tests for PHP 8.2

---

AUTHORS
CHANGELOG.md

I did my best, but there have been a few commits in the past 2+ years 😬

Changelog v0.12.2

---

.github/workflows/docker-latest.yml

Docker build: add ARM64 platform and bump Github action version

---

tpl/default/pluginsadmin.html

Documentation: fix broken link to 3rd party plugins

---

tpl/default/page.header.html

Bulk action form and input were loaded with autofocus feature on all pages, preventing other input field to benefit from autofocus feature.
Fixes #1974

Fix autofocus: load bulk action input on linklist only

---

doc/md/Usage.md

- fixes https://github.com/shaarli/Shaarli/issues/1982

doc: improve docs on usage of OR operator in tags search

---

.github/workflows/docker-pr.yml

- fixes https://github.com/shaarli/Shaarli/issues/1800
- do not push, only check that the image builds correctly

tools: github actions: build docker images on pull requests

---

Makefile
README.md
application/bookmark/BookmarkInitializer.php
application/legacy/LegacyLinkDB.php
composer.json
doc/md/index.md
inc/languages/de/LC_MESSAGES/shaarli.po
inc/languages/fr/LC_MESSAGES/shaarli.po
inc/languages/jp/LC_MESSAGES/shaarli.po
inc/languages/ru/LC_MESSAGES/shaarli.po
inc/languages/zh_CN/LC_MESSAGES/shaarli.po
index.php
mkdocs.yml
tpl/default/page.footer.html
tpl/vintage/page.footer.html

- fixes https://github.com/shaarli/Shaarli/issues/1758

correct usage of hyphens in all occurences of 'super fast, database-free'

---

doc/md/Community-and-related-software.md

Relates to [compact theme issue comment](https://github.com/shaarli/Shaarli/issues/1328#issuecomment-1789098080).

Add shaarli-stack theme to Community-and-related-software.md

---

doc/md/Community-and-related-software.md

doc: themes: remove unmaintained themes

---

README.md

- fixes https://github.com/shaarli/Shaarli/issues/2033

doc: remove bountysource badge

---

doc/md/Shaarli-configuration.md

- fixes https://github.com/shaarli/Shaarli/issues/2034

doc: document general.download_max_size/timeout configuration settings

---

doc/md/Troubleshooting.md

- related https://github.com/shaarli/Shaarli/issues/531
- fixes https://github.com/shaarli/Shaarli/issues/989

doc: troubleshooting: automatic title retrieval fails when it is set by javascript

---

AUTHORS
CHANGELOG.md

@nodiscc I have to release a major version because we're dropping support for multiple PHP 7 versions.

Changelog v0.13.0 + authors

---

README.md

Note: replace stable + latest with release branch (only latest version)

Bump badge version in README

---

.github/workflows/trivy-release.yml
Makefile
README.md

- add badge to README
- any time a new vulnerability is found by this workflow, means it is probably time to update Shaarli's base docker image and perform a new release, and/or update npm dependencies (npm audit fix) or composer dependencies (composer update)
- similar jobs already exist in the pipeline for master/latest docker image but will not raise an error
- fixes https://github.com/shaarli/Shaarli/issues/1531
- see https://github.com/nodiscc/Shaarli/actions/runs/6996115659/job/19031654100 and https://github.com/nodiscc/Shaarli/actions/runs/6996115659/job/19031654195 for example job outputs

github actions: run daily trivy security scans on release docker image, composer/yarn dependencies

---

doc/md/Usage.md

- ref. https://github.com/shaarli/Shaarli/discussions/2057

doc: usage: add opensearch/browser search engine integration instructions

---

AUTHORS
CHANGELOG.md
doc/md/dev/Development.md

- ref. https://github.com/shaarli/Shaarli/issues/2105

doc: update CHANGELOG for v0.14.0

---

Dockerfile
tests/docker/alpine319/Dockerfile

- https://www.alpinelinux.org/posts/Alpine-3.18.10-3.19.5-3.20.4-released.html
- https://www.alpinelinux.org/posts/Alpine-3.18.11-3.19.6-3.20.5-3.21.2-released.html
- https://www.alpinelinux.org/posts/Alpine-3.18.12-3.19.7-3.20.6-3.21.3-released.html

docker: update base alpine image to v3.19.7

---

composer.lock
package.json
phpunit.xml
yarn.lock

Update packages due to audits and compatibility
Update phpunit to new format

update packages and phpunit

---

SECURITY.md

- fixes https://github.com/shaarli/Shaarli/issues/2148

doc: add SECURITY.md

---

application/netscape/NetscapeBookmarkUtils.php

- fixes https://github.com/shaarli/Shaarli/security/advisories/GHSA-vwcv-9hj3-8982

fix insufficient filename sanitization in bookmarks import form

---

application/front/controller/visitor/TagCloudController.php

- https://github.com/shaarli/Shaarli/security/advisories/GHSA-7w7w-pw4j-265h

fix reflected XSS via searchtags parameter
