shaarli/Shaarli

inc/shaarli.css, tpl/changepassword.html, tpl/configure.html, tpl/daily.html, tpl/export.html, tpl/import.html, tpl/linklist.html, tpl/linklist.paging.html, tpl/page.footer.html, tpl/picwall.html, tpl/tagcloud.html
#64 
Every page should pass W3C validator. Further tests should be done, but that's a good start. Thanks to @virtualtam.
=> Make Shaarli's template W3C compliant #64

index.php, tpl/changetag.html, tpl/editlink.html, tpl/linklist.html
* removed the language attribute on the script element since it is obsolete and we can safely omit it.
* make QRCode JS works with IE :
* behave as a normal link if canvas aren't supported (<=IE8)
* default parameter values in JS aren't widely supported (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters ), use this method instead: http://stackoverflow.com/a/148918/1484919
* dataset isn't supported in IE9
* addEventListener works with IE9+ and other browsers
=>  Remove language attribute on script tag and improve QRCode JS

index.php, tpl/includes.html, tpl/install.html, tpl/linklist.html
Fixes the remaining W3C validation errors reported in #64
All pages:
- add `urlencode` when passing the version to a custom stylesheet;
- set meaningful values of `alt` and `title` for QR-Code images.
Install page:
- the form's `action` attribute must be non-empty;
- the `valign` attribute is deprecated.
To validate the install page, you may need to comment the session check section at the beginning of the `install()` method in `index.php` (else, the session check will fail, and there'll be nothing to validate ;-) ).
=> w3c: fix HTML syntax errors

index.php
Fixes Port/server config problems - see: https://github.com/shaarli/Shaarli/issues/17
* Use SERVER_NAME instead of HTTP_HOST to define current URL (in serverUrl()
* Use SERVER_NAME instead of HTTP_HOST while setting up cookies
=> Fixes Port/server config problems

inc/shaarli.css, index.php, tpl/configure.html, tpl/tools.html
The option to see the shortlinks or permalinks has been added to the configuration panel. It is a simple checkbox
This option is disabled by default (meaning that shortlinks are the default)
Updated writeConfig() to save this option
Also fixed a slight typo in config.html.
=> Feature: enable/disable permalinks for RSS

COPYING, README.md, inc/reset.css, inc/shaarli.css, tpl/includes.html, tpl/page.footer.html
* remove version number display from main page
* update project URL in footer, fixes https://github.com/shaarli/Shaarli/issues/89
* update copyright notice in the footer
* mention origins of the fork in README, fixes https://github.com/shaarli/Shaarli/issues/105
* update License section in the README
* remove screenshots as mediacru.sh is down
=> Update README and Shaarli's footer

.gitignore, Makefile, composer.json
Here's a Makefile to run the static analysis tools mentioned in #95.
* Several configurations are available for each tool, I've tried to keep them as relevant as possible.
* Tools are managed with Composer, which is pretty straightforward to use.
There's also a Travis config draft, untested (Travis is currently under maintenance).
Edit: Travis is back! Here's what a build looks like: https://travis-ci.org/virtualtam/Shaarli/builds/52341101
=> Code quality: Makefile to run static code checkers

doc/Mentions-of-Shaarli-in-"the-press".md, index.php
The deletion is related to Windows not handling quotes in filenames, see
#179. It shouldn't delete the real file. Probably. Check it out.
=> Display notes as absolute urls.

index.php
This bug was introduced by #168 and #169 combined. This PR allows to setup the UTF8 locale if it exists.
Another way around is to add utf8_encode() in the template while formatting the date.
=> #193 add UTF8 by default to autoLocale

index.php
On "The Daily Shaarli" page (index.php?do=daily), the date is "Tuesday
30, November 1999" if no articles have been published/shared.
This patch checks the parameter ($linkdate) before the mktime call to
prevent and generate the "day 0" string.
mktime(0,0,0,0,0,0) returns 943916400 (hum?)
Since this error only appears when nothing has been published, feel free to ignore this pull request.
I didn't test widely.
=> Daily - Display date as today if no articles published

index.php, tpl/editlink.html, tpl/tools.html
As discussed in #101, here comes the PR.
The wording of the button might be debatable, I didn't know how to call it, you might have better ideas than I do.
I didn't do any browser detection either since that would make this patch a bit more complex, I'm not sure it's worth it since it doesn't break other browsers.
=> Add Firefox Social API to the tools. Fixes #101.

.gitignore, Makefile, application/.htaccess, application/LinkDB.php, application/Utils.php, composer.json, index.php, phpunit.xml, tests/.htaccess, tests/LinkDBTest.php, tests/UtilsTest.php, tests/utils/ReferenceLinkDB.php
Hi all!
This is a first polished draft to bring unitary tests to Shaarli :smile:
To help revewing the PR, and bring some logic to the test-writing process, I've split this comment in 3 sections:
* the bare commit message: what's been done
* how to configure your dev environment to run tests (as well as syntax analysis, aka lint)
* implementation details
* technical choices and assumptions
* coding guidelines followed
As usual, feel free to comment the PR, make suggestions, ask for explanations... ^^
```
LinkDB: move to a proper file, add test coverage
Relates to #71
LinkDB
- move to application/LinkDB.php
- code cleanup
- indentation
- whitespaces
- formatting
- comment cleanup
- add missing documentation
- unify formatting
Test coverage for LinkDB
- constructor
- public / private access …
```
=> LinkDB: move to a proper file, add test coverage

index.php, tpl/daily.html
It only concerns the date of the day in the main title.
Fixes #182
Note that daily RSS feed is not generated through templates. Date are still hard formatted in that case.
To template maintainers @AkibaTech @alexisju @dhoko @kalvn @misterair @Vinm @vivienhaese ([list found here](https://github.com/shaarli/Shaarli/wiki#themes--templates), don't know if it's accurate), if this PR is merged, you'll have to update your daily template like I did here [L16](https://github.com/shaarli/Shaarli/commit/4de71445d3d174b5ef3462a1c4470a95cc00017e#diff-ebe9fdf25292625e325af9880371a141R16).
=> Daily page: date format in template

application/LinkDB.php
As discovered in #241 the recent changes in LinkDB broke compatibility with PHP 5.3. This pull requests restores this.
=> Restore compatibility with php 5.3 

application/LinkDB.php, index.php, tests/LinkDBTest.php, tests/utils/ReferenceLinkDB.php
Relates to #218
Removes "hidden" access to the following variables:
- $GLOBALS['config']['datastore']
- PHPPREFIX
- PHPSUFFIX
NOTE: may need to be rebased after merging #238
=> LinkDB: do not access global variables

tests/LinkDBTest.php
=> LinkDBTest: only check that the datastore is created and non-empty

application/LinkDB.php, tests/LinkDBTest.php, tests/utils/ReferenceLinkDB.php
=> LinkDB: prefix private members with an underscore

index.php
Relates to #255, see [l. 41](https://github.com/shaarli/Shaarli/commit/e92f1ba59edb9fd60b185dc633e64a62dffe3b04#diff-828e0013b8f3bc1bb22b4f57172b019dL41)
This issue was reported by @alexisju on Gitter, it prevents setting Shaarli options such as custom themes.
With the following configuration:
* Apache 2
* PHP 5.6.10
* user sites enabled, e.g. `/home/user/public_html/somedir` is served as `http://localhost/~user/somedir`
* Apache user is `http`
I've set up a simple environment using the [albinomouse-template](https://github.com/alexisju/albinomouse-template) repository, on the [am-dev](https://github.com/alexisju/albinomouse-template/tree/am-dev) branch:
```bash
$ cd ~/public_html
$ git clone https://github.com/virtualtam/Shaarli.git -b fix/read-config shaarli
$ pushd shaarli/tpl
$ git …
```
=> Fix: data/config.php was not imported

.travis.yml, README.md, application/Config.php, application/TimeZone.php, application/Utils.php, index.php, tests/ConfigTest.php, tests/LinkDBTest.php, tests/TimeZoneTest.php, tests/UtilsTest.php
Relates to #250
Modifications
- add PHP 5.3 to Travis environments
- rewrite array declarations: explicitely use array() instead of []
- move checkPHPVersion to application/Utils.php
- move timezone functions to application/TimeZone.php
- improve test coverage
- bump required version from 5.1.0 to 5.3.x
=> PHP: ensure 5.3 compatibility

.travis.yml, Makefile
Fixes #288
Modifications:
- call `make clean` explicitely to clean the workspace
- add `make clean` to Travis instructions
=> Makefile: do not call `clean` before `test`

Makefile
Relates to #95
Usage
- list available standards
`$ ./vendor/bin/phpcs -i`
- run PHPCS against a given standard
`$ make PHPCS_<standard>`
Examples
```bash
$ make PHPCS_PSR1
$ make PHPCS_Zend
```
As the target is generic (parametrizable), I chose a different naming style to avoid conflicts with the existing `code_sniffer_<type>` targets.
=> Add a generic rule to run PHPCS against different coding standards

application/Cache.php, application/CachedPage.php, application/LinkDB.php, index.php, tests/CacheTest.php, tests/CachedPageTest.php, tests/LinkDBTest.php, tests/utils/ReferenceLinkDB.php
Modifications
- rename `pageCache` to `CachedPage`
- move utilities to `Cache`
- do not access globals
- apply coding rules
- update LinkDB and test code
- add test coverage
=> CachedPage: move to a proper file, add tests

.travis.yml
Reminder:
- PHP 5.4 is reaching End Of Life on 2015-09-14
- PHP 7 RC1 has been released on 2015-08-21
- PHP 7 RC2 is due on 2015-09-03
- ...
- PHP 7 is to be released on 2015-11-12
=> travis: add PHP 7 to the tested environments

application/Utils.php, index.php, tests/UtilsTest.php
* Add a function to validate session ID.
* Generate a new session ID if an invalid token is passed.
related to #298 
ping @TeamAlexandriZ
=> Avoid Full Path Disclosure error on session error.

application/Url.php, index.php, tests/UrlTest.php
PHP doesn't seem to autoconvert objects to strings when they're use as array indexes.
Fixes regression introduced in d9d776af19fd0a191f82525991dafbb56e1bcfcb
Note that this feature is pretty light: if URL's strings doesn't match perfectly, it won't be regognize (eg. HTTP/HTTPS).
#325
=> Fixes #325 - Shaarli does not recognize saved links

application/Utils.php, tests/UtilsTest.php
Fixes shaarli/Shaarli#335 - Wrong login/password since v0.5.2
Regression introduced in 06b6660a7e8891c6e1c47815cf50ee5b2ef5f270
@virtualtam @nodiscc This is a critical bug. Should we recreate v0.5.2 with this commit included?
=> Allow uppercase letters in PHP sessionid format

application/Utils.php, index.php, tests/UtilsTest.php, tests/utils/ReferenceSessionIdHashes.php
[EDITED]
Improves #306
Relates to #335 & #336
Duplicated by #339
Issues:
- PHP regenerates the session ID if it is not compliant
- the regex checking the session ID does not cover all cases
- different algorithms: md5, sha1, sha256, etc.
- bit representations: `4, 5, 6`
Fix:
- `index.php`:
- remove `uniqid()` usage
- call `session_regenerate_id()` if an invalid cookie is detected
- regex: support all possible characters - `[a-zA-Z,-]{2,128}`
- tests: add coverage for all algorithms & bit representations
See:
- http://php.net/manual/en/session.configuration.php#ini.session.hash-function
- https://secure.php.net/manual/en/session.configuration.php#ini.session.hash-bits-per-character
- http://php.net/manual/en/function.session-id.php
- …
=> Session ID: extend the regex to match possible hash representations

application/HttpUtils.php, index.php, tests/HttpUtilsTest.php
Relates to #333
Modifications:
- move HTTP utils to 'application/HttpUtils.php'
- simplify logic
- replace 'http_parse_headers_shaarli' by built-in 'get_headers()'
- remove superfluous '$status' parameter (provided by the HTTP headers)
- apply coding conventions
- add test coverage (unitary only)
=> HTTP: move utils to a proper file, add tests

application/Utils.php, index.php, tests/UtilsTest.php
Not related, but already discussed in #354:
* allow redirection on relative urls in generateLocation
cf #357
=> Fixes #356 -  adding a link should return added link's hash

plugins/demo_plugin/custom_demo.css, plugins/demo_plugin/demo_plugin.js, plugins/demo_plugin/demo_plugin.php, plugins/demo_plugin/field.html
This plugin try to cover Shaarli's plugin API entirely.
Can be used by plugin developper to make their own.
=> PLUGIN demo_plugin

index.php, plugins/readityourself/readityourself.php, plugins/wallabag/wallabag.php
Before this, calling writeConfig() would have write error messages in data.php, because it uses 'plugins' array which is used for plugin configuration.
Causing the message error to appear everytime.
=> Bugfix: do not store plugin errors in data.php

index.php
bookmarklet fields weren't correctly escaped
(Sorry about the previous PR, my branches got mixed up)
=> Fixes #382: Bookmarklet can not retrieve title when there is a quotation mark in it

application/ApplicationUtils.php, application/FileUtils.php, application/LinkDB.php, index.php, tests/ApplicationUtilsTest.php, tests/LinkDBTest.php
Relates to #40
Additions:
- FileUtils: IOException
- ApplicationUtils:
- check if Shaarli resources are accessible with sufficient permissions
- basic test coverage
- index.php:
- check access permissions and redirect to an error page if needed:
- before running the first installation
Modifications:
- LinkDB:
- factorize datastore write code
- check if the datastore
(exists AND is writeable) OR (doesn't exist AND its parent dir is writable)
- raise an IOException if needed
=> tools: check file/directory permissions for Shaarli resources

index.php
cleanup: remove json_encode() (built-in since PHP 5.2)
See http://php.net/manual/en/function.json-encode.php
=> json_encode removed

.gitignore, Makefile, application/ApplicationUtils.php, index.php, tests/ApplicationUtilsTest.php, tests/CacheTest.php, tests/CachedPageTest.php, tests/LinkDBTest.php
Relates to #372
Modifications:
- move checkUpdate() to ApplicationUtils
- reduce file I/O operations during version checks
- apply coding conventions
- add test coverage
Tools:
- create a sandbox directory for tests
=> application: refactor version checks, move to ApplicationUtils

application/ApplicationUtils.php, index.php, tests/ApplicationUtilsTest.php, tpl/page.footer.html
Relates to #372
Relates to #390
=> application: default to the "stable" branch for update checks

inc/shaarli.css, plugins/qrcode/qrcode.css, plugins/qrcode/qrcode.html, plugins/qrcode/qrcode.php, plugins/qrcode/shaarli-qrcode.js
* fixes a regression misplacing QRCode popup introduced in 6a6f6c32e5876a347a806cc43d25596b9257765b (`position: relative` was missing).
* adds a fancy transition on popup openning from @alexisju [proposition](https://github.com/shaarli/Shaarli/commit/6a6f6c32e5876a347a806cc43d25596b9257765b#commitcomment-14943549).
=> Fixes QRCode style

application/LinkDB.php, plugins/qrcode/qrcode.php, tests/plugins/PlugQrcodeTest.php
Fixes #414 and avoid usage of redirector in QRCode.
Also fixed a bug with URL encoding.
=> QRCode plugin: use url instead of real_url

.gitattributes
TL;DR: let Git cleverly handle line endings and diffs, tidy release archives a bit ;-)
Features:
- enforce LF (Unix) line endings
- omit dev/test resources & code from Git(Hub) archives
- treat minified resources (CSS, JS) as binaries to avoid cluttered diffs
Resources:
- http://git-scm.com/docs/gitattributes
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes
- https://help.github.com/articles/dealing-with-line-endings/
- http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/
- https://github.com/Danimoth/gitattributes
=> Add a .gitattributes to ease repository management

application/LinkDB.php, application/LinkFilter.php, application/Utils.php, index.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/utils/ReferenceLinkDB.php, tpl/linklist.html
* introduce class LinkFilter to handle link filter operation (and lighten LinkDB).
* handle 'private only' in filtering.
* update template to prefill search fields with current search terms.
* coding style.
* unit test (mostly move from LinkDB to LinkFilter).
PS: preparation for #358 #315 and 'AND' search.
=> Link filter refactoring

application/ApplicationUtils.php, application/HttpUtils.php, application/LinkUtils.php, application/Url.php, index.php, tests/HttpUtils/GetHttpUrlTest.php, tests/LinkUtilsTest.php, tests/Url/UrlTest.php
* `get_http_url()` renamed to `get_http_response()`.
* Use the same HTTP context to retrieve response headers and content.
* Follow HTTP 301 and 302 redirections to retrieve the title (default max 3 redirections).
* Add `LinkUtils` to extract titles and charset.
* Try to retrieve charset from HTTP headers first (new), then HTML content.
* Use mb_string to re-encode title if necessary.
=> Fixes #410 - Retrieve title fails in multiple cases

application/Utils.php, tests/UtilsTest.php
Fixes #436
Modifications:
- remove calls to strval() on safe data
- update the date format: 'Y/m/d_H:i:s' => 'Y/m/d H:i:s'
=> Logging: improve formatting to enable fail2ban parsing

application/Utils.php, tests/UtilsTest.php
=> fix: use PHP_EOL for carriage returns in file logs

application/Config.php, application/PluginManager.php, application/Router.php, inc/plugin_admin.js, inc/shaarli.css, index.php, plugins/addlink_toolbar/addlink_toolbar.meta, plugins/archiveorg/archiveorg.meta, plugins/demo_plugin/demo_plugin.meta, plugins/playvideos/playvideos.meta, plugins/qrcode/qrcode.meta, plugins/readityourself/readityourself.meta, plugins/readityourself/readityourself.php, plugins/wallabag/wallabag.meta, plugins/wallabag/wallabag.php, tests/ConfigTest.php, tests/PluginManagerTest.php, tests/plugins/test/test.meta, tpl/pluginsadmin.html, tpl/tools.html
From the administration panel, users can:
* See all plugin name and description available.
* Enable/disable plugins.
* Change loading order of their plugins (affects for example shaares icon order).
* Affect and change plugins parameters.
Every plugin needs a `<plugin_name>.meta` file which is in fact an `.ini` file (`KEY="VALUE"`) to be listed in plugin administration.
Each file contain two keys:
* `description`: plugin description
* `parameters`: user parameter names, separated by a `;`.
> Note: In PHP, `parse_ini_file()` seems to want strings to be between by quotes `"` in the ini file.
There is a new page: `pluginsadmin.html`. It needs to be added to your theme. I'll update documentation later.
Aside from classic RainTPL loops, plugins order is handle by JavaScript. You can use …
=> Fixes #378 - Plugin administration UI.

index.php
If the checkbox is not set at installation, the key is never saved in `config.php` so it raises a warning.
=> Add a default value to ENABLE_UPDATECHECK to avoid unnecessary warning

index.php
Fixes a bug where accessing `$GLOBALS['plugins']` raised a warning if no previous plugin settings has been set.
=> Initialize plugin parameters array to avoid unnecessary warning.

application/Config.php, application/LinkDB.php, application/LinkFilter.php, application/Updater.php, index.php, tests/ConfigTest.php, tests/Updater/DummyUpdater.php, tests/Updater/UpdaterTest.php
* contains methods designed to be run once.
* is able to upgrade the datastore or the configuration.
* is based on methods names, stored in a JSON file (updates.json).
* begins with existing function 'mergeDeprecatedConfigFile()' (options.php).
To give a bit more context, I stumbled upon a problem when working on tag filter features (#315 & #358). I have to update existing tags to make sure they don't start with a `.` or a `-`. To be able to do this, I had to run a regexp against all link's tag.
Obviously, I couldn't run this for each request. Otherwise, a few other upgrades like this would had start to impact performances.
After rewriting everything twice, I end up with this solution. Let me know what you think.
=> Introduce the Updater class which

index.php
Remove unnecessary escape().
Not a security issue because:
* Referer is already escaped in the hidden field in editlink.
* Referer URL is not displayed after that.
* Any malicious parameter will be escaped before being displayed in templates.
And code cleanup
#440
=> Fixes #440 - 404 error after editing a link

application/LinkDB.php, application/LinkFilter.php, application/Updater.php, index.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/Updater/UpdaterTest.php, tests/utils/ReferenceLinkDB.php
> This PR is based on #442. Please review the second commit only.
* Searching '-mytag' will now exlude all shaares with 'mytag' tag.
* All tags starting with a '-' are renamed without it (through the Updater).
* Unit tests.
Minor code changes:
* LinkDB->filter() can now take no parameters (get all link depending on logged status).
* tagsStrToArray() is now static and filters blank tags.
Partial fix of #358
=> Add exclusion in tag search

index.php
* Use Collator class to sort tags using the locale (in PECL intl, included in most PHP installation).
* Use strcasecmp if Collator is not found.
Both sorts are case insensitive.
#456
=> Fixes #456: Tag cloud does not sort tags (fully) alphabetically

index.php
Spaces at the start of shaares can be intended. Eg: markdown plugin.
#468 
\+ coding style
=> Fixes #468: don't trim description

application/LinkDB.php, index.php, tpl/dailyrss.html
Closes #270
Modifications:
- replace custom date parsing by DateTime calls
- use proper date formatting for RSS feeds
Deletions:
- linkdate2timestamp()
- linkdate2rfc822()
- linkdate2iso8601()
=> cleanup: use DateTime to format dates

application/Utils.php, index.php
Only send LC_COLLATE to Collator and check that no error occured.
Also: Apply the locale to all categories and move autolocale to Utils.php
#481 
PS troll: `intl_is_failure(intl_get_error_code())`. Really?!
=> Fixes #481: tag cloud fatal error

application/LinkDB.php, application/LinkFilter.php, inc/shaarli.css, index.php, tests/LinkFilterTest.php, tpl/linklist.html
* Partial fix of #449
* Current use case: search term + click on tag.
* LinkFilter now returns all links if no filter is given.
* Unit tests.
**Template change:** the way search is handled changes in templates.
=> Allow crossed search between terms and tags

application/HttpUtils.php, tests/HttpUtils/ServerUrlTest.php
Going through multiple reverse proxy will store multiple scheme and port in HTTP header separated by a comma. Shaarli will use the first one to generate server_url.
#477
=> Fixes #477: support multi reverse proxy with comma syntax

plugins/markdown/markdown.php
It allows to respect the choice that has been made to not populate the link-description div when there's no content. And it makes things easier in terms of design to avoid unnecessary padding and margin when there is nothing to display.
=> Avoids populating a markdown empty container if there's no description.

application/FeedBuilder.php, application/LinkDB.php, application/LinkFilter.php, application/Router.php, application/Updater.php, application/Utils.php, index.php, plugins/demo_plugin/demo_plugin.php, tests/FeedBuilderTest.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/Updater/UpdaterTest.php, tests/utils/ReferenceLinkDB.php, tpl/configure.html, tpl/feed.atom.html, tpl/feed.rss.html
This PR is a bit huge, please look at the commit log to review it. I've tried to split everything in different commits to make it understandable.
To sum it up:
* RSS and Atom feeds are now sharing the same code, in FeedBuilder.
* They're generated through RainTPL templates. 
* It's now covered by unit tests.
* There is a new plugin hook called before rendering feeds.
* The `ENABLE_RSS_PERMALINKS` setting in administration has been reworded.
Fixes #273 
Note that this doesn't concern Daily RSS feed.
PS: [tig](https://github.com/jonas/tig) is awesome.
=> Refactor RSS feeds generation, and do it through templates

index.php, tpl/tagcloud.html
* Force the number format with number_format().
* Reduce the size deciment number to 2.
=> Fixes #526: bad font size separator in tagcloud with some locale

application/LinkDB.php, index.php, tests/LinkDBTest.php
* New config: `$GLOBALS['config']['REDIRECTOR_URLENCODE']` (default `true`).
* Parameter added to LinkDB constructor.
* Fixes a bug with urlencode and escaped url.
* In `index.php`, LinkDB is now instanciate once for `importFile()` and `showDaily()`.
* TU
#480
=> Fixes #480: add an option to urlencode redirector URL

application/NetscapeBookmarkUtils.php, index.php, tests/NetscapeBookmarkUtilsTest.php, tpl/export.bookmarks.html, tpl/export.html
Relates to https://github.com/shaarli/netscape-bookmark-parser/issues/5
Fixes:
- respect the Netscape bookmark format "specification"
Modifications:
- [application] introduce the NetscapeBookmarkUtils class
- [template] export           - improve formatting, rename export selection parameter
- [template] export.bookmarks - template for Netscape exports
TODO:
- test coverage
=> Refactor Netscape bookmark exporting

application/LinkFilter.php
Arrays are key-value maps. We should reindex the array after a filter
since we are using the key and count to do array access in filterTags.
An example would be searching for "foo, bar", after the array filter,
our array is actually (0 -> foo, 2 -> bar) which will cause an error
when trying to access $searchtags[1].
=> Fix error when filtering search tags

application/HttpUtils.php, application/LinkUtils.php, application/Url.php, index.php, tests/HttpUtils/GetHttpUrlTest.php, tests/Url/UrlTest.php
see #531 for details
Almost everything is now working, except:
* hosts which seem to have an anti-bot policy (2 in #531).
* hosts which have a very high latency (1 in #531).
=> Fixes #531 - Title retrieving is failing with multiple use case

application/TimeZone.php, index.php, tests/TimeZoneTest.php
During install or configuration, if `UTC/UTC` is selected, use the fallback value, `UTC`, which is a valid timezone.
Fixes #547
=> Use correct 'UTC' timezone

application/NetscapeBookmarkUtils.php, index.php, tests/NetscapeBookmarkUtilsTest.php, tpl/export.html
Relates to #102
Additions:
- application:
- export: allow prepending note permalinks with the instance's URL
- test coverage
Modifications:
- export template: switch to an HTML form
- link selection (all/private/public)
- prepend note permalinks with the instance's URL
=> Export: allow prepending notes with the Shaarli instance's URL

README.md, tpl/page.footer.html
Because Shaarli isn't a delicious clone. Also it's 2016 and delicious is more or less dead.
I've also added a 'nofollow' instruction to the docs, because if you search Shaarli inyour favorite search engine you might notice a bunch of links to the documentation from random Shaarli's instances.
=> Remove delicious from Shaarli description

index.php
Fixes #561 
This will require an extra click, but no data is lost, and the current behaviour doesn't really make sense.
=> Don't redirect to ?post if ?addlink is reached while logged out

plugins/markdown/markdown.css
To make it more visible. Fixes #511
=> Markdown: inline code background color

application/LinkUtils.php, application/PageBuilder.php, index.php, tests/LinkUtilsTest.php, tpl/page.header.html
Also moved PageBuilder to its own file to clean up `index.php`.
Fixes #247
=> Private links counter in the header

application/Url.php, tests/Url/UrlTest.php
As seen on https://lafibre.info/online/datacenter-dc3-diliad/ and many other websites.
=> Url.php: remove unwanted ?PHPSESSID= URL parameters

application/LinkDB.php, tests/FeedBuilderTest.php, tests/LinkDBTest.php, tests/utils/ReferenceLinkDB.php
When retrieving all tags, case differences will be ignored.
This affects:
* tag cloud
* tag autocompletion
=> Fixes #497: ignore case difference between tags

plugins/markdown/markdown.php, tests/plugins/PluginMarkdownTest.php
A private tag is never loaded for visitor, making this feature useless. 
This tag is no longer private, *but* always hidden in linklist.
From Gitter:
> **@nodiscc**: I've read about a possible bug in the markdown plugin, just a reminder to check for this http://shaarli.guiguishow.info/?PAenmg
> **@ArthurHoaro**: Oh. That was stupid. The .nomarkdown tag is private, so it's never loaded for visitors.
EDIT: backquotes in the commit message didn't work very well.
=> The "nomarkdown" tag is no longer private

application/LinkDB.php, application/LinkFilter.php, application/LinkUtils.php, application/Utils.php, plugins/markdown/markdown.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/LinkUtilsTest.php, tests/UtilsTest.php, tests/utils/ReferenceLinkDB.php
* Hashtag are auto-linked with a filter search
* Supports unicode
* Compatible with markdown (excluded in code blocks)
Fixes #278 
PS: it's a new search type, different from `?searchtag`, which isn't really useful.
=> Hashtag system

tests/Url/UrlTest.php
This fixes a small typo in IDN-related testing method.
=> Fix typo in test method name

application/PageBuilder.php, index.php
- Fixed title config key
- Page title (in head tag) is no longer set through the config manager
=> Fixes #600 - Shaarli's title is not set with the new config manager

.gitignore, Makefile, composer.json
See #607
- reference https://github.com/shaarli/netscape-bookmark-parser as a Composer VCS repository
- allow generating custom release archives (tarball, zip) containing 3rd-party dependencies
TODO:
- check on a dummy fork that GitHub-generated release archives can be replaced/superseded by manually uploaded archives
- tweak `git describe` output (used to name archives)
- archiving commands are currently _quiet_ - set them to be _verbose_?
=> Reference netscape-bookmark-parser & allow generating custom release archives

application/PageBuilder.php, index.php
Token will be generated for every pages instead of generating and assigning one for a few pages specifically.
Use case: javascript login form in the header template (accessible anywhere) in the webdesign branch.
=> Generate a token for every pages

application/Languages.php, index.php, tests/LanguagesTest.php
It matches the API of ngettext(), regarding #121. 
It allows to call the translation function in the future templates.
=> Initialize a translation function

application/HttpUtils.php
=> Added (and set as default) a cURL-based method for fetching HTTP content

composer.json
Relates to https://github.com/shaarli/Shaarli/pull/607
Relates to https://github.com/shaarli/Shaarli/pull/612
Relates to https://github.com/shaarli/netscape-bookmark-parser/issues/15
Modification:
- reference the "shaarli" vendor repository on Packagist instead of
overriding the upstream package with an SCM repository
See https://packagist.org/packages/shaarli/netscape-bookmark-parser
=> Composer: reference shaarli/netscape-bookmark-parser from Packagist

application/NetscapeBookmarkUtils.php, index.php, tests/NetscapeBookmarkUtils/BookmarkExportTest.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php, tests/NetscapeBookmarkUtils/input/netscape_basic.htm, tests/NetscapeBookmarkUtils/input/netscape_nested.htm, tests/NetscapeBookmarkUtils/input/no_doctype.htm, tests/NetscapeBookmarkUtils/input/same_date.htm, tpl/import.html
Relates to #607
Relates to #608
Relates to #493 (abandoned)
Additions:
- use Composer's autoload to load 3rd-party dependencies under vendor/
Modifications:
- [import] replace the current parser with a generic, stable parser
- move code to application/NetscapeBookmarkUtils
- improve status report after parsing
- [router] use the same endpoint for both bookmark upload and import dialog
- [template] update bookmark import options
- [tests] ensure bookmarks are properly parsed and imported in the LinkDB
- reuse reference input from the parser's test data
See:
- https://github.com/shaarli/netscape-bookmark-parser
- https://getcomposer.org/doc/01-basic-usage.md#autoloading
=> Refactor bookmark import using a generic Netscape parser

application/NetscapeBookmarkUtils.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php, tests/NetscapeBookmarkUtils/input/internet_explorer_encoding.htm
Modifications:
- [application][tests] NetscapeBookmarkUtils: more permissive doctype detection
The IE bookmark exports contain extra escape sequences, which can be observed
by binary comparison of the reference input data used in tests:
```bash
$ cmp -b -l -n 8 netscape_basic.htm internet_explorer_encoding.htm
1  74 <    357 M-o
2  41 !    273 M-;
3 104 D    277 M-?
4 117 O     74 <
5 103 C     41 !
6 124 T    104 D
7 131 Y    117 O
8 120 P    103 C
```
=> Fix: ensure Internet Explorer bookmark dumps can be imported

application/PluginManager.php, application/config/ConfigPlugin.php, inc/shaarli.css, plugins/wallabag/wallabag.meta, tests/PluginManagerTest.php, tests/config/ConfigPluginTest.php, tests/plugins/test/test.meta, tpl/pluginsadmin.html
* Plugin parameter can contain a description in their meta file under the key:
`parameter.<param_name>="<description>"`
* Update the plugin admin template to display it.
* Description added for the Wallabag plugin.
Fixes #463
=> Add a description to plugin parameters

docker/development/Dockerfile, docker/production/Dockerfile
Relates to https://github.com/shaarli/Shaarli/pull/612
Relates to https://github.com/shaarli/Shaarli/pull/624
See https://github.com/shaarli/Shaarli/wiki/Server-requirements
Modifications:
- [all][env] set $TERM=dumb to avoid debconf-related issues
- [all][pkg] install ca-certificates
- [all][pkg] cleanup APT cache after installing packages
- [dev] refactor Dockerfile
- [prod][master][php] use Composer to resolve PHP dependencies
- [prod][master] refactor Dockerfile
=> Docker: update dependencies, introduce Composer

index.php
Closes https://github.com/shaarli/Shaarli/issues/645
=> composer: display an error message if the autoload script is missing

application/HttpUtils.php, index.php, tests/HttpUtils/GetIpAdressFromProxyTest.php
* Add a new settings (which needs to be manually set): `security.trusted_proxies`
* On login failure, if the `REMOTE_ADDR` is in the trusted proxies, try to retrieve the forwarded IP in headers.
* If found, the client address is added in ipbans, else we do nothing.
Fixes #409
EDIT: Doc updated.
=> Add trusted IPs in config and try to ban forwarded IP on failed login

application/FeedBuilder.php, application/LinkDB.php, index.php, tests/FeedBuilderTest.php, tests/utils/ReferenceLinkDB.php, tpl/feed.atom.html, tpl/feed.rss.html, tpl/linklist.html
**Templates**
The update date is now save when a link is updated. This date is passed to the linklist template, as a timestamp, under the key `updated_timestamp`.
I've updated the default templates to show the update date when the creation date is hovered.
**Feeds**
*RSS*
RSS feeds doesn't support an update date for each item, so we use the ATOM extension, like this:
<atom:modified>[date in ATOM format]</atom:modified>
*ATOM*
* The tag `updated` in the header can be updated with update dates.
* The tag `published` has been added for each element.
* The tag `updated` present in each items is now changed if a link is updated.
> Note: the RFC states that all items in ATOM feeds MUST include an `updated` tag, so it will be initialized with the `published` tag value.
Fixes #563
=> Save link update dates and render it in templates and feeds

application/PageBuilder.php, application/PluginManager.php, index.php, plugins/demo_plugin/demo_plugin.php, plugins/readityourself/readityourself.php, plugins/wallabag/wallabag.php, tests/plugins/PluginReadityourselfTest.php, tests/plugins/PluginWallabagTest.php
All plugins can optionally add an init function named `pluginname_init()` which is called when the plugin is loaded.
This function is aware of the config, and can return initialization errors, which are displayed in the header template.
Note that the previous error system hack no longer work.
=> New init function for plugins, supports errors reporting

tpl/daily.html, tpl/dailyrss.html, tpl/export.bookmarks.html, tpl/feed.atom.html, tpl/feed.rss.html, tpl/linklist.html, tpl/page.header.html, tpl/picwall.html, tpl/tagcloud.html
Relates to https://github.com/shaarli/Shaarli/issues/613
Before: `{loop="someVariable"}`
After:  `{loop="$someVariable"}`
=> Cleanup: explicitely loop over PHP variables in templates

plugins/isso/isso.css, plugins/isso/isso.html, plugins/isso/isso.meta, plugins/isso/isso.php, tests/plugins/PluginIssoTest.php
Use Isso client to let visitors comments on permalinks
Note: also affect private links because links can previously commented links can be set to private and the other way around.
Note bis: It's not beautifully integrated for now.
ping #181
=> Isso comments plugin

CHANGELOG.md, Makefile
Relates to https://github.com/shaarli/Shaarli/pull/608
TODO:
@ArthurHoaro [wrote](https://github.com/shaarli/Shaarli/pull/608#issuecomment-253752275):
> @virtualtam: the archives generated with this target contain the Shaarli files "directly", while Github auto-generated archives contain them in a sub-folder. Is there a reason behind this? If not it might be a good idea to preserve the same behaviour.
Now I remember: I left the archives as generated by `git-archive` -that is, without an internal `Shaarli-XXX` prefix. While the prefix itself is quite easy to add through the `--transform` flag, this makes adding extra files (the `vendor` dir) a bit tedious/hackish (pick your favourite adjective ^^).
=> Update release archive generation

application/LinkDB.php, application/NetscapeBookmarkUtils.php, application/Updater.php, index.php, tests/LinkDBTest.php, tests/utils/ReferenceLinkDB.php
A bit of cleanup of `LinkDB`'s internals before working on #351:
- apply coding conventions (no leading underscore in privates' names)
- simplify method names
- explicit (public) method visibility
=> LinkDB: code cleanup

CHANGELOG.md, docker/development/Dockerfile, docker/development/nginx.conf, docker/production/Dockerfile, docker/production/nginx.conf, docker/production/stable/Dockerfile, docker/production/stable/nginx.conf
Relates to #681
Changed:
- nginx+php-fpm: set maximum upload size to 10 MiB
Fixed:
- nginx: set the favicon location
See:
- https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
- https://secure.php.net/manual/en/ini.core.php#ini.post-max-size
- https://secure.php.net/manual/en/ini.core.php#ini.upload-max-filesize
- http://serverfault.com/a/352861
=> Docker: fix & improve nginx+php-fpm configuration

application/.htaccess, cache/.htaccess, data/.htaccess, docker/.htaccess, pagecache/.htaccess, tests/.htaccess, tmp/.htaccess
If `mod_version` is enabled, the previous syntax will apply for Apache <2.4.
If not, the new syntax is used by default.
Fixes #676 
~~TODO: mention this in the server documentation.~~
[Wiki updated](https://github.com/shaarli/Shaarli/wiki/Server-configuration#htaccess)
=> .htaccess files: support Apache 2.4+ syntax

index.php, tpl/tools.html
Firefox now refuses to add a social component if the page is not loaded using HTTPS ([see here](https://bugzilla.mozilla.org/show_bug.cgi?id=1190828#c2)).
This PR simply hides this option if the page is not loaded using HTTPS.
=> Disable Firefox Social in the tools section if the page is not loaded using HTTPS.

plugins/markdown/README.md, plugins/markdown/markdown.php, tests/plugins/PluginMarkdownTest.php
* pass taglist as an array for `stripNoMarkdownTag`
* make sure we match exactly `nomarkdown` tag
Fixes #689
=> Markdown: fixes feed rendering with nomarkdown tag

tpl/feed.atom.html
Content not starting directly with CDATA can be misinterpreted by some feed parsers.
=> Remove new line between content tag and CDATA in ATOM feed

plugins/addlink_toolbar/addlink_toolbar.css, plugins/addlink_toolbar/addlink_toolbar.html, plugins/addlink_toolbar/addlink_toolbar.php, plugins/demo_plugin/custom_demo.css, plugins/demo_plugin/demo_plugin.php, plugins/playvideos/playvideos.html, plugins/playvideos/playvideos.php, tpl/linklist.html, tpl/linklist.paging.html, tpl/page.header.html
- buttons_toolbar: now expect links represented by an array instead of HTML content
- fields_toolbar: now expect a form represented by an array instead of HTML content
Default templates updated accordingly
EDIT: Updated:
- action_plugin: now expect links represented by an array instead of HTML content
=> Improve theme dependent plugin placeholders:

application/FeedBuilder.php, application/LinkDB.php, application/LinkFilter.php, application/LinkUtils.php, application/NetscapeBookmarkUtils.php, application/Updater.php, application/Utils.php, index.php, plugins/isso/isso.php, tests/FeedBuilderTest.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/NetscapeBookmarkUtils/BookmarkExportTest.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php, tests/Updater/UpdaterTest.php, tests/plugins/PluginIssoTest.php, tests/utils/ReferenceLinkDB.php, tpl/daily.html, tpl/editlink.html, tpl/linklist.html
First of all, it was way harder than what I though, tests appreciated.
Links now use an incremental unique numeric identifier. This ID is persistent and must never change. ArrayAccess is used to match the link ID with the array keys (see the comment at the top of LinkDB for more details).
Key 'created' added for each link, with creation date as a DateTime object. 'updated' is now also a DateTime.
I also added a persistent 'shorturl' key to all links to preserve existing permalinks. "Small hashes" are now generated once using the date (`YYYYMMDD_hhmmss`) and the ID to avoid collision.
The updater does its work and everything should be transparent to users. Just in case, it makes a backup of the datastore before anything.
Take a look at individual commits for something more readable.
@mro, …
=> Link ID refactoring

index.php
I'll cherry pick this commit to create a v0.8.2 release, since it's a major issue.
fixes #713
=> Fix a regression: permalinks change when old links are edited

.htaccess, .travis.yml, CHANGELOG.md, application/Updater.php, application/Utils.php, application/api/ApiMiddleware.php, application/api/ApiUtils.php, application/api/controllers/ApiController.php, application/api/controllers/Info.php, application/api/exceptions/ApiAuthorizationException.php, application/api/exceptions/ApiBadParametersException.php, application/api/exceptions/ApiException.php, application/api/exceptions/ApiInternalException.php, application/config/ConfigManager.php, composer.json, index.php, tests/Updater/UpdaterTest.php, tests/UtilsTest.php, tests/api/ApiMiddlewareTest.php, tests/api/ApiUtilsTest.php, tests/api/controllers/InfoTest.php, tpl/configure.html, tpl/install.html
**Warning**: PHP requirement upgraded to PHP 5.5 - #599 
- REST API routes are handle by Slim.
- Every API controller go through ApiMiddleware which handles security.
- First service implemented `/info`, for example/tests purpose.
This is a first step regarding #655. It's actually pretty easy to use. :)
---
All requests must include a valid JWT token in their header.
You can use this script to generate a token (valid during 9min):
``` php
<?php
function generateJwtToken($secret)
{
$header = base64_encode('{
"typ": "JWT",
"alg": "HS512"
}');
$payload = base64_encode('{
"iat": '. time() .'
}');
$signature = hash_hmac('sha512', $header .'.'. $payload , $secret);
return $header .'.'. $payload .'.'. $signature;
}
echo generateJwtToken('jaimeLePate');
```
---
New settings (which will be updated …
=> REST API structure using Slim framework

application/FeedBuilder.php, composer.json, index.php, plugins/pubsubhubbub/README.md, plugins/pubsubhubbub/hub.atom.xml, plugins/pubsubhubbub/hub.rss.xml, plugins/pubsubhubbub/pubsubhubbub.meta, plugins/pubsubhubbub/pubsubhubbub.php, tests/FeedBuilderTest.php, tests/plugins/PluginPubsubhubbubTest.php, tpl/feed.atom.html, tpl/feed.rss.html
- Adds placeholders in feeds templates to specify which hub is used (`render_feed` hook).
- Retrieve the publisher lib with Composer.
- Notify the hub everytime a link is saved (`save_link`).
- Adds a default PHP fallback if `cURL` is not installed.
- Silently log exceptions.
TODO:
Fixes #459
=> Move Pubsubhub to a default plugin

application/LinkFilter.php, application/Utils.php, index.php, tests/UtilsTest.php
* Private tags: make sure empty tags are properly filtered
* Search results:
* Use preg_split instead of function combination
* Add normalize_spaces to remove extra whitespaces displaying empty tags search
Fixes #722
=> Fixes presence of empty tags for private tags and in search results

index.php
Hi!
I've started toying a bit with the API to prepare the nginx configuration and have stumbled upon a few quirks:
- Slim namespaces (addressed in this PR)
- side-effects of using 2 routers + URL rewriting: accessing non-existent resources leads to unexpected results (e.g. try accessing `http://my.supah.shaarley.io/titi/toto/tutu/tatapouf`)
- (non-standard?) expected JWT header / format:
- current: `jwt: <my jwt token>`
- [documented](https://jwt.io/introduction/#how-do-json-web-tokens-work-): `Authorization: Bearer <my jwt token>`
I've used the following script (derived from #666) to run checks:
```php
<?php
function generateJwtToken($secret)
{
$header = base64_encode('{
"typ": "JWT",
"alg": "HS512"
}');
$payload = base64_encode('{
"iat": '. time() .'
}');
$signature = …
```
=> API: fix Slim namespaces

application/Router.php, index.php, tpl/linklist.html
Use a GET form to delete links: harmonize with edit_link and preparation for #585
Bug fixes:
* LinkDB element can't be passed as reference, fix warning:
> PHP Notice:  Indirect modification of overloaded element of LinkDB has no effect
* Resource cache folder setting wasn't set correctly
Fixes #718
=> Bugfixes on link deletion, and use a GET form

.gitattributes, .github/mailmap, AUTHORS, COPYING, Makefile
Added:
- AUTHORS file listing Shaarli contributors
- Makefile target to list contributors from Git commit data
Changed:
- Simplify COPYING by using a single "Shaarli Community" entry
- Bump year to 2017
=> Add an AUTHORS file, simplify COPYING, bump year to 2017

application/api/ApiMiddleware.php, tests/api/ApiMiddlewareTest.php
Relates to https://github.com/shaarli/Shaarli/pull/731
Added:
- require the presence of the 'Authorization' header
Changed:
- use the HTTP Bearer Token authorization schema
See:
- https://jwt.io/introduction/#how-do-json-web-tokens-work-
- https://tools.ietf.org/html/rfc6750
- http://security.stackexchange.com/q/108662
`Authorization: Bearer <JWT token>`
Python + [Requests](http://docs.python-requests.org/en/master/user/advanced/#custom-authentication) + [Requests-JWT](https://github.com/tgs/requests-jwt)
```python
#!/usr/bin/env python3
"""Shaarli REST API test client"""
import calendar
import json
import time
import requests
from requests_jwt import JWTAuth
def main():
"""Main entrypoint"""
uri = 'http://localhost/~user/shaarli/api/v1/info'
secret = 'ch4ng3m3!'
auth = JWTAuth(secret, …
```
=> API: expect JWT in the Authorization header

application/Updater.php
To access LinkDB items with its ArrayAccess implementation, the IDs must be consistent, which isn't the case before `updateMethodDatastoreIds()` execution. v0.6.4 method `updateMethodRenameDashTags()` was accessing it, so an upgrade <0.6.4 to >0.8.x was failing.
This just move the minor update `RenameDashTags` after the IDs update.
Note: This updater mechanism has its limit, and at some point, we'll probably have to ask users to export/import their data if they're using a very old version, otherwise it might become unmaintainable.
=> Fixes #775: LinkDB do not access LinkDB before ID system migration

application/api/controllers/Links.php, tests/api/controllers/LinksTest.php
Service `GET links`, the parameter `private` is replaced by `visibility`. See [the documentation](http://shaarli.github.io/api-documentation/#links-links-collection-get).
=> REST API - getLinks: support the visibility parameter

tpl/default/tools.html
Carriage returns turns into space in some cases. The name of the bookmarklet, once in the browser bookmarks, is preceded by a space.
=> Removes spaces before bookmarklet's name

application/Updater.php, plugins/markdown/README.md, plugins/markdown/markdown.php, tests/Updater/UpdaterTest.php, tests/plugins/PluginMarkdownTest.php, tests/plugins/resources/markdown.html
This setting allows to escape HTML in markdown rendering or not.
The goal behind it is to avoid XSS issue in shared instances.
More info:
* the setting is set to true by default
* it is set to false for anyone who already have the plugin enabled
(avoid breaking existing entries)
* improve the HTML sanitization when the setting is set to false - but don't consider it XSS proof
* mention the setting in the plugin README
This need to be backported and released in v0.7.x and v0.8.x.
This PR is high priority.
=> Add markdown_escape setting

application/Updater.php, application/api/ApiMiddleware.php, application/config/ConfigIO.php, application/config/ConfigJson.php, application/config/ConfigManager.php, application/config/ConfigPhp.php, application/config/ConfigPlugin.php, composer.json, index.php, tests/ApplicationUtilsTest.php, tests/PluginManagerTest.php, tests/Updater/UpdaterTest.php, tests/api/ApiMiddlewareTest.php, tests/api/controllers/GetLinkIdTest.php, tests/api/controllers/GetLinksTest.php, tests/api/controllers/InfoTest.php, tests/config/ConfigJsonTest.php, tests/config/ConfigManagerTest.php, tests/config/ConfigPhpTest.php, tests/config/ConfigPluginTest.php, tests/plugins/PluginIssoTest.php, tests/plugins/PluginMarkdownTest.php, tests/plugins/PluginPubsubhubbubTest.php, tests/plugins/PluginQrcodeTest.php, tests/plugins/PluginReadityourselfTest.php, tests/plugins/PluginWallabagTest.php
Namespaces have been introduced with the REST API, and should be generalized
to the whole codebase to manage object scope and benefit from autoloading.
See:
- https://secure.php.net/manual/en/language.namespaces.php
- http://www.php-fig.org/psr/psr-4/
=> application: introduce the Shaarli\Config namespace

.travis.yml, Makefile, application/Utils.php, composer.json, phpunit.xml, tests/UtilsTest.php, tests/languages/bootstrap.php, tests/languages/de/UtilsDeTest.php, tests/languages/en/UtilsEnTest.php, tests/languages/fr/UtilsFrTest.php, tpl/default/linklist.html, tpl/vintage/linklist.html
Use php-intl extension to display datetimes a bit more nicely, depending on the locale.
What changes:
* the day is no longer displayed
* day number and month are ordered according to the locale
* the month label is complete instead of first 3 letters
* the timezone is more readable (UTC+1 instead of CET)
I also ran into issues using `autoLocale()` so I improved it:
- create arrays_combination function to cover all cases
- add the underscore separator in the regex
- add `utf8` encoding in addition to `UTF-8`
=> Improve datetime display

application/Utils.php, tests/languages/de/UtilsDeTest.php, tests/languages/en/UtilsEnTest.php, tests/languages/fr/UtilsFrTest.php
Fix a very obvious bug: `implode('implode', ...)`. I was a bit in a hurry.
Multiple improvements to `autoLocale()`:
* support multiple locales send in the header
* defaults to `en_US` if the given locale isn't installed
Heavy unit tests coverage.
=> Fix autoLocale error and cover it with unit tests

plugins/markdown/markdown.php, tests/plugins/PluginMarkdownTest.php
Adapted from https://github.com/shaarli/Shaarli/pull/785
=> security: escape HTML entities when using Markdown

application/config/ConfigManager.php, application/config/exception/MissingFieldConfigException.php, application/config/exception/UnauthorizedConfigException.php, tests/config/ConfigManagerTest.php
General rule: all classes must be in a dedicated file ; file containing only functions shouldn't have a namespace.
This PR is based on #792, check only the last commit.
=> Move config exception to dedicated classes with proper namespace

application/config/ConfigJson.php, application/config/ConfigManager.php, tests/config/ConfigJsonTest.php
PHP 5.5 allow us to use `json_last_error_msg()` instead of a cryptic ID.
Error:
An error occurred while parsing configuration JSON file (data/config.json.php): error code #4
➜ Syntax error
Please check your JSON syntax (without PHP comment tags) using a JSON lint tool such as [jsonlint.com](http://jsonlint.com).
=> Proper error if the conf file is invalid instead of fatal error

.gitignore, composer.lock
When `composer update` is run, Composer will retrieve latest dependencies and generate a new `composer.lock`. With `composer install`, it will retrieve the exact same version present in `composer.lock`, i.e. the latest `composer update` versions.
This should prevent us from running in the same issue we did with #779 
TODO:
=> Include composer.lock in git files

tpl/default/js/shaarli.js
Explanation: an ID with a leading digit isn't a valid CSS selector
=> Theme: JS - Fix a bug preventing edit margin suppression to work

application/Utils.php, index.php, tests/UtilsTest.php, tpl/vintage/import.html
It was multiplying a string containing a letter.
Moved function to Utils.php and display a human readable limit size
And unit test o/
=> Fix a warning generated in return_bytes function and refactor it

application/Utils.php, index.php, tests/UtilsTest.php, tpl/default/import.html
I forgot that the upload size is also handled by an hidden field, which doesn't support human readable values and is currently blocking any upload.
=> Use raw bytes for upload size hidden input

application/PageBuilder.php, application/TimeZone.php, index.php, tests/TimeZoneTest.php, tpl/default/configure.html, tpl/default/install.html, tpl/default/js/shaarli.js, tpl/vintage/configure.html, tpl/vintage/css/shaarli.css, tpl/vintage/install.html, tpl/vintage/js/shaarli.js, tpl/vintage/page.footer.html
The goal of this is to be able to adapt the timezone form
in template without hacking the HTML already rendered.
* there are two arrays available:
* `continents` which contains only a list of available continents
* `cities` which contains a list of available timezone cities, associated with their continent
Note: 
* there are two distinct array because RainTPL doesn't support nested loop very well.
* without JS, all cities are displayed
**To template maintainers**: [this commit](https://github.com/shaarli/Shaarli/commit/6c7fc3b54d4b1c6130a1734cd126ba11dec371d3) sums up pretty well how to apply this change.
=> Change timezone data structure send to the templates

application/FileUtils.php, application/History.php, application/LinkDB.php, application/NetscapeBookmarkUtils.php, application/config/ConfigManager.php, application/exceptions/IOException.php, index.php, tests/FileUtilsTest.php, tests/HistoryTest.php, tests/LinkDBTest.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php
Feature: keep an history of the latest action made in a Shaarli instance.
Use case: REST API service `history`.
Details:
* Saved by default in `data/history.php`.
* Same format as the datastore (base64 compressed data in PHP comment).
* Traced events:
* save/edit/delete link
* change settings or plugins settings
* rename/delete tag
* the events are kept for 1 month
What's saved for each event:
* Event type
* DateTime
* Identifier (optional, e.g. Link ID)
=> History mechanism

application/FileUtils.php, application/History.php, application/Updater.php, application/api/ApiMiddleware.php, application/api/controllers/ApiController.php, application/api/controllers/History.php, application/api/controllers/Links.php, index.php, tests/HistoryTest.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php, tests/api/controllers/DeleteLinkTest.php, tests/api/controllers/GetLinkIdTest.php, tests/api/controllers/GetLinksTest.php, tests/api/controllers/HistoryTest.php, tests/api/controllers/InfoTest.php, tests/api/controllers/PostLinkTest.php, tests/api/controllers/PutLinkTest.php, tests/utils/ReferenceHistory.php
* datetime is now store as an object in history store file
* Reset the history file due to datetime format change
* History: fix entries order
* Add settings history entry only when they're updated
=> Add history entries for API endpoint

application/NetscapeBookmarkUtils.php
The shorturl would be set to null, generating a lot of warnings and breaking permalinks
=> Fix a bug happening when importing links with override option

application/PageBuilder.php, index.php
Currently, tag autocompletion only works on the link list and the tagcloud. Since the new theme provides a search bar in any page, the tags must be set.
=> Inject tag list everywhere to make autocomplete work on the fixed search bar

application/LinkDB.php, application/PageBuilder.php, index.php, tests/LinkDBTest.php, tpl/default/css/shaarli.css, tpl/default/tagcloud.html, tpl/vintage/tagcloud.html
The counters in the tag cloud become clickable.
A demo of this feature can be seen here: https://chezsoi.org/shaarli/?do=tagcloud&searchtags=Python
If you like the idea, please tell me which tests I need to add to this PR ;)
=> Adding the ability to display subtags in the tagcloud

application/FeedBuilder.php, application/LinkDB.php, application/LinkFilter.php, application/Utils.php, index.php, tests/LinkDBTest.php, tests/LinkFilterTest.php, tests/api/controllers/GetLinksTest.php, tests/api/controllers/InfoTest.php, tests/utils/ReferenceLinkDB.php, tpl/default/linklist.html, tpl/vintage/linklist.html
Fixes #784
From now, searching for tags with an empty value will return only not tagged links,
with the search bar showing `x results [not tagged]`.
Note that using the api, the searchtags request parameter must be set to `false` to get the same result.
Also, `filterSearch()` in `LinkDB` has been simplified.
=> Empty tag search will look for not tagged links

application/Url.php, application/config/ConfigManager.php, index.php, plugins/markdown/markdown.php, tests/Url/WhitelistProtocolsTest.php, tests/plugins/PluginMarkdownTest.php, tests/plugins/resources/markdown.html, tests/plugins/resources/markdown.md
- for Shaare
- for markdown description links and images
Not whitelisted protocols will be replaced by `http://`
=> Add a whitelist of protocols for URLs

tpl/default/js/shaarli.js
`{noparse}` is no longer required since the JS function is now in `shaarli.js`.
Also, include the trailing slash in the post URL.
Fixes #895
=> Fix Firefox Social button in the default theme

.travis.yml
Travis is currently migrating its default build environment from `precise` to `trusty`, hence Brazilian Portuguese being the default locale in some tests... wait, wat?
https://travis-ci.org/shaarli/Shaarli/builds/259870211
I'm not sure for now whether it's an issue with Travis environments, or we need to refresh our CI configuration to match the new environments. In the meantime, let's stick to a working CI setup :)
---
See https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
=> travis: explicitly set the build dist to `precise`

Makefile
=> fix: use pinned dependency revisions when generating release archives

composer.json, composer.lock
Without this setting, composer would download dependencies depending on the PHP version installed on the system ; and generate a `composer.lock` accordingly.
E.G. I was getting doctrine/instantiator 1.1, which requires at least PHP 7.1.
=> Fix PHP version configuration in composer.json

tpl/default/tag.list.html
It isn't really useful and doesn't look good if there isn't enough tags
=> Remove the 2nd green 'sort by' row in link list

tpl/default/tools.html
Currently the note bookmarklet of the default theme is broken due to using *unescaped* double quotes inside the double quotes of the `href=""` attribute. 
This fixes the issue by using single quotes (that's what the *Shaare link* bookmarklet already does)
fixes #933
=> fixed note bookmarklet

application/config/ConfigManager.php, doc/md/Shaarli-configuration.md, index.php, tpl/default/loginform.html, tpl/vintage/loginform.html
- the default state for the login page's 'remember me' checkbox can now be configured
- adapted the default and vintage theme to consider the new setting
- added documentation for the new setting
fixes #936
=> new setting: default value for 'remember me' checkbox

application/HttpUtils.php, index.php, tests/HttpUtils/IsHttpsTest.php, tpl/default/js/shaarli.js
Fixes #929 
Also make `$sslenabled` work behind a reverse proxy.
Without `HTTP_X_FORWARDED_PORT` check, `$sslenabled` might be set to false even though the user is using HTTPS, thus disabling Firefox Social block display.
This needs to be tested behind HTTPS + reverse proxy.
=> Firefox Social title: Use document.title instead of RainTPL variable

application/config/ConfigManager.php, doc/md/Shaarli-configuration.md, index.php
- new setting *force_login* added and documented
- if both, *force_login* and *hide_public_links* are set to true, all requests
(except for the feeds) are redirected to the login page
I hope you can live with this adaption :wink:
fixes #952
=> added option to redirect all anonymous users to login page

Makefile, doc/md/Unit-tests-Docker.md, docker/test/alpine36/Dockerfile, docker/test/debian8/Dockerfile, docker/test/debian9/Dockerfile, docker/test/ubuntu16/Dockerfile, mkdocs.yml
Hi!
I've created a bunch of Dockerfiles to help debugging #843 & #845 and allow running Shaarli tests (`make <stuff>`) under different containerized environments.
Q: Would there be interest in including these resources in the main repository?
Usage:
```bash
$ cd /path/to/shaarli
$ cd docker/test/debian9
$ docker build -t shaarli-test:debian9 .
$ cd /path/to/shaarli
$ docker run -v $PWD:/shaarli shaarli-test:debian9 docker_test
```
What's behind the curtains:
- each image provides a base OS + PHP packages + composer
- the local workspace is mapped to the container's `/shaarli/` directory
- the files are rsync'd to avoid running tests as `root` (which bypasses any permission issue)
- the tests are run within the container
---
Relates to https://github.com/shaarli/Shaarli/issues/843
Added:
- …
=> docker: add alpine,debian,ubuntu test images

application/LinkFilter.php, tests/api/controllers/GetLinksTest.php
- when searching for tags you can now include '*' as wildcard placeholder
- new search reduces overall overhead when filtering for tags
- fixed combination with description tag search ('#' prefix)
- tests added
fixes #937
=> wildcard tag search support

application/LinkUtils.php, tests/LinkUtilsTest.php
With markdown plugin disabled
relates to #966
=> Fix parsing for description links with parentheses

tpl/default/js/shaarli.js
We manually reset the scroll position, to avoid height = 'auto' jump to the top
Fixes #971
=> Fix jumpy textarea with long content in post edit

application/ApplicationUtils.php, application/PageBuilder.php, application/Updater.php, index.php, tpl/default/includes.html, tpl/default/page.footer.html
The hash is generated using the same salt as the one used for credentials (1 salt per instance)  in order to avoid exposing the instance version.
Fixes #965 
-----
Rename shaarli_version constant to uppercase
=>  Add a version hash for asset loading to prevent browser's cache issue

application/History.php, application/NetscapeBookmarkUtils.php, tests/NetscapeBookmarkUtils/BookmarkImportTest.php
With large imports it has a large impact on performances and isn't really useful.
Instead, write an IMPORT event, which let client using the history service resync its DB.
-> 15k link import done in 6 seconds.
Fixes #985
=> Don't write History for link import

.editorconfig, .gitattributes
EditorConfig allows specifying indentation, line feed and encoding
properties according to the type of file being edited.
Most editors support it out-of-the-box, or can benefit from it through a
plugin.
See:
- http://editorconfig.org/
- https://github.com/editorconfig/editorconfig
- https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
=> Add EditorConfig configuration

doc/md/docker/shaarli-images.md, docker/alpine/Dockerfile.latest, docker/alpine/IMAGE.md
This implies the following changes:
- `shaarli/shaarli:latest` will now point to the `latest` release
- `shaarli/shaarli:master` will point to the `master` branch
=> docker: add 'latest' image

application/PageBuilder.php, application/SessionManager.php, application/Utils.php, index.php, tests/SessionManagerTest.php, tests/UtilsTest.php
Relates to #324
See commit messages for details
=> Refactor session management utilities

tpl/default/configure.html
This feature is pretty much useless these days as browsers have builtin features to support the thag "<meta name='referrer'", so keep the setting page as clean as possible.
Also, avoid advertising it too much, because I'm pretty sure it doesn't work very well with markdown descriptions (as Parsedown have some trouble regarding URL detection (without MarkDown link tag)).
=> Remove redirector setting from Configure page

Makefile, doc/md/Download-and-Installation.md, doc/md/Unit-tests.md
* In preparation of #930 work
* Remove/reorder duplicate documentation from Makefile/Unit-tests.md/Download-and-Installation.md (composer information is now in Unit-tests.md)
* Installation using git: add composer requirement to all git installation procedures, add python3-virtualenv requirement
* Styling (horizontal rulers, spacing, descriptive headers)
=> documentation cleanup

application/SessionManager.php, tests/SessionManagerTest.php, tests/utils/FakeConfigManager.php
Relates to https://github.com/shaarli/Shaarli/pull/1005
Changed:
- pass a copy of the ConfigManager instance instead of a reference
- move FakeConfigManager to a dedicated file
- update tests
=> Improve SessionManager constructor and tests

application/HttpUtils.php, tests/HttpUtils/ServerUrlTest.php
=> Force HTTPS if the original port is 443 behind a reverse proxy

doc/md/Community-&-Related-software.md
Hi Everyone,
I have just created my first Shaarli plugin, and if you all agree, we could list it on the 3rd party plugins page in the docs. I am going to use the plugin on a daily basis, so I will not abandon it until I use Shaarli.
https://github.com/immanuelfodor/shaarli-descriptor
=> Adding 3rd party plugin 'shaarli-descriptor' to docs

tpl/default/pluginsadmin.html
$counter is a special variable in RainTPL used in loops
=> Fix an issue preventing the Save button to appear for plugin parameters

doc/md/Community-&-Related-software.md
Hi Everyone,
I spent the last couple of days creating a markdown editor plugin to Shaarli, if you think it is helpful for others, we can include it in the documentation. This plugin is a lot more complex thing than PR #1042, but I think it well worth the effort. It improved the overall link adding/editing experience a lot for me, especially on mobile. It was a pain every time to get the symbols on my Android keyboard, but now it is a single click.
https://github.com/immanuelfodor/shaarli-markdown-toolbar
=> Adding 3rd party plugin 'markdown-toolbar' to docs

application/HttpUtils.php, application/LinkUtils.php, index.php, tests/LinkUtilsTest.php
Use CURLOPT_WRITEFUNCTION to check the response code and content type (only allow HTML).
Also extract the title and charset during downloading chunk of data, and stop it when everything has been extracted.
Closes #579
=> Extract the title/charset during page download, and check content type

application/Languages.php, index.php
As stated in the docs:
> LC_MESSAGES for system responses (available if PHP was compiled with libintl)
Fixes #1067
=> Use LC_COLLATE instead of LC_MESSAGES if php-intl is not installed

application/PageBuilder.php, application/Updater.php, inc/languages/fr/LC_MESSAGES/shaarli.po, index.php, tpl/default/css/shaarli.css, tpl/default/linklist.paging.html, tpl/vintage/linklist.paging.html
When the key filter is clicked once, it only displays private link. When it is clicked on again, it becomes red and only public links are displayed. Another click and all links are displayed. The current visibility status is shown in the search banner
Fixes #1030
=> Add a filter to only display public links

application/LoginManager.php, index.php, tests/LoginManagerTest.php, tests/utils/FakeConfigManager.php, tpl/default/loginform.html, tpl/vintage/loginform.html
Relates to https://github.com/shaarli/Shaarli/issues/324
Added:
- Add the `LoginManager` class to manage logins and bans
Changed:
- Refactor IP ban management
- Simplify logic
- Avoid using globals, inject dependencies
Fixed:
- Use `ban_duration` instead of `ban_after` when setting a new ban
=> Refactor login / ban management

docker/alpine/Dockerfile.latest, docker/alpine/Dockerfile.master
Relates to https://github.com/shaarli/Shaarli/issues/755
Relates to https://github.com/shaarli/Shaarli/pull/1072
See:
- https://docs.docker.com/develop/develop-images/multistage-build/
- https://hub.docker.com/r/library/composer/
- https://github.com/composer/docker
- https://github.com/docker-library/docs/tree/master/composer
=> docker: introduce multi-stage image build (master, latest)

docker/alpine/Dockerfile.latest
When Dockerfiles were migrated to multi-stage build (#1085), the `chown nginx` part was omited from the `latest` Dockerfile.
This prevents the `latest` image to run properly, crashing with such error:
```
[02-Mar-2018 13:53:50] WARNING: [pool www] child 18 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught RainTpl_Exception: Cache directory tmp/doesn't have write p
ermission. Set write permission or set RAINTPL_CHECK_TEMPLATE_UPDATE to false. More details on http://www.raintpl.com/Documentation/Documentation-for-PHP-developers/Configuration
/ in /var/www/shaarli/inc/rain.tpl.class.php:321"
- -  02/Mar/2018:13:53:50 +0000 "GET /index.php" 500
[02-Mar-2018 13:53:50] WARNING: [pool www] child 18 said into stderr: "Stack trace:"
[02-Mar-2018 13:53:50] WARNING: [pool www] child …
```
=> Fix permission issue introduced with multi-stage build

docker/alpine/Dockerfile.armhf.latest, docker/alpine/Dockerfile.armhf.master, docker/alpine/Dockerfile.latest, docker/alpine/Dockerfile.master
This change allows to see the nginx logs with `docker logs <container>`.
This trick didn't work with the Debian image.
=> Nginx logs to stdout for Docker images

doc/md/Upgrade-and-migration.md
I can't see the version.php file, so I guess the documentation should point to shaarli_version.php
=> Documentation : Fix current version file name

.htaccess
On some Apache HTTPD setups where the CGI/FastCGI mode is used, the HTTP header
containing the JWT token is not forwarded, which results in the following error
when attempting to use the REST API:
"401 Not authorized: JWT token not provided"
This patch allows forwarding the 'Authorization' header. An alternative would
be to use the `CGIPassAuth` directive to allow all authorization headers to be
forwarded.
See:
- https://secure.php.net/manual/en/features.http-auth.php#114877
- https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request
- https://stackoverflow.com/questions/13387516/authorization-header-missing-in-django-rest-framework-is-apache-to-blame
- https://stackoverflow.com/questions/17018586/apache-2-4-php-fpm-and-authorization-headers
- …
=> httpd: always forward the 'Authorization' header

plugins/markdown/markdown.php
The removal of `on=...` attributes is rather destructive because it is performed without really parsing the html. E.g. when using the markdown plugin and having something like `[text](http://domain.tld?action=value)` will result in garbled html. This tiny change fixes this a bit, only removing when preceded by whitespace, which will always be the case with JS event handlers. So will work in more/most cases, still the best method would be using a html parser, which I think most will consider overkill.
=>  Fix removal of on=... attributes from html (generated from markdown)

.editorconfig, .travis.yml
Related to [this comment](https://github.com/shaarli/Shaarli/pull/1072#discussion_r170757510).
I chose to use stages here instead of matrix because, in my understanding, using matrix would require a bunch of `if` in the `script` section.
The only downside I see here is that the JS tests don't run in parallel, they wait for the `test` stage to be successfully completed.
=>  Use Travis stages to run JS tests separately 

application/HttpUtils.php, application/LoginManager.php, application/PageBuilder.php, application/SessionManager.php, application/security/LoginManager.php, application/security/SessionManager.php, composer.json, index.php, tests/HttpUtils/ClientIpIdTest.php, tests/LoginManagerTest.php, tests/security/LoginManagerTest.php, tests/security/SessionManagerTest.php, tests/utils/FakeConfigManager.php, tpl/default/linklist.html, tpl/default/linklist.paging.html, tpl/default/page.footer.html, tpl/default/page.header.html, tpl/default/tag.list.html, tpl/vintage/daily.html, tpl/vintage/linklist.html, tpl/vintage/linklist.paging.html, tpl/vintage/page.footer.html, tpl/vintage/page.header.html
This is the second step towards refactoring the login and session system (see #1008), and makes room for future improvements: login/logout/session management is currently mixed up between `LoginManager` and `SessionManager`, with `ConfigManager` acting as a data backend.
Despite the PR being in progress, feel free to comment (esp. on variable and method naming) and suggest improvements!
- Refactored functions:
- `allIPs()` => `client_ip_id`
- `fillSessionInfo()` => `SessionManager->storeLoginInfo()`
- `setup_login_state()` => `LoginManager->checkLoginState()`
- `check_auth()` = > `LoginManager->checkCredentials()`
- group security features under the `Shaarli\Security` namespace
- refactor session and cookie duration mechanism (aka `staySignedIn`, `longlastingsession`)
- refactor user …
=> Refactor user login and session management

application/LinkDB.php, tests/LinkDBTest.php
=> Fix order of tags with the same number of occurrences

doc/md/Community-&-Related-software.md
Add a button to install with Yunohost in a one-click way.
Related to : #1162
=> Other platform integration: add Yunohost install badge

Dockerfile, doc/md/docker/shaarli-images.md
This avoids regenerating the thumbnail cache when renewing and/or updating the application container.
=> Docker: expose a volume for the thumbnail cache

doc/md/Upgrade-and-migration.md
Install page is not correctly linked
=> Upgrade-and-migration.md: typo installation link

tpl/default/pluginsadmin.html, tpl/vintage/page.footer.html
Fixes #930 
Documentation path is hardcoded to the local copy, therefore the documentation has to be present.
=> Fix broken documentation links in page footer and pluginsadmin

mkdocs.yml
Relates to https://github.com/shaarli/Shaarli/issues/1179
See:
- https://www.mkdocs.org/user-guide/configuration/#build-directories
- https://github.com/rtfd/readthedocs.org/issues/4314
=> Disable MkDocs' strict mode for ReadTheDocs builds to pass

tpl/default/page.header.html
The alt does not provide any useful information for screenreader users. It just adds noise.
=> empty alt on logo image

tpl/default/tools.html
Redundant titles are an accessibility issue and should be avoided.
See : https://accessibilitytips.com/2008/04/14/avoiding-redundant-title-attributes/
=> Delete redundant titles

application/Updater.php, index.php
Do not try to alter the datastore by updating thumbnails if the user isn't logged in.
Also, do not enable thumbnails if PHP GD extension is not installed/loaded.
Fixes #1198
=> Fix issue 'You are not authorized to add a link' with thumbnails enabled

composer.lock
Fixes #1201 
Related to #1196 
Full changelog:
* Add a setting to force Apache version for htaccess syntax
* PHPDocs improvements
* Parameter `PATH_TYPE` has been removed
* WebThumbnailer no longer try to resolve relative path to thumbnails, it now relies on provided `path.cache` setting
=> Upgrade composer - web-thumbnailer v1.3.0

composer.lock
WT has php-gd as a requirement, which isn't available in composer docker image
=> Fix docker build

doc/custom_theme/main.html, doc/md/Server-configuration.md, mkdocs.yml
by customizing the "readthedocs" mkdocs theme
https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
This prevents indexing/crawling of the documentation pages by search engines/robots that respect the [robots meta-tag specification](https://developers.google.com/search/reference/robots_meta_tag).
This should work even behind a reverseproxy since it does not rely on generating HTTP headers server-side.
Note: This might affect the public documentation hosted at https://shaarli.readthedocs.io/ !
Fixes https://github.com/shaarli/Shaarli/issues/1177
=> add "noindex, nofollow" HTML robots meta-tag to documentation pages

application/PageBuilder.php, plugins/markdown/markdown.php, tests/plugins/PluginMarkdownTest.php, tpl/default/includes.html, tpl/vintage/includes.html
Includes:
- og:title
- og:type -> article
- og:image -> if there is a thumbnail
- og:url -> permalink
- og:description -> first 300 chars of raw description
- article:published_time
- article:modified_time
- article:tag -> one OG meta tag for each shaare tag
Fixes #258
=> Add OpenGraph meta tags on permalink page

doc/custom_theme/main.html
Fixes #1177
The `url` template filter is [only supported in Mkdocs 1.0+](https://github.com/mkdocs/mkdocs/blob/master/docs/about/release-notes.md#internal-refactor-of-pages-files-and-navigation)
Readthedocs.org uses Mkdocs `0.17.3 ` while `make htmldoc` fetches the [latest version from pypi](https://pypi.org/project/mkdocs/) which is `1.0.4`.
Following https://github.com/shaarli/Shaarli/pull/1220, building the docs fails with https://readthedocs.org/projects/shaarli/builds/7886340/
=> Revert part of #1220

doc/md/Sharing-content.md
Firefox Share integration has been removed in https://github.com/shaarli/Shaarli/pull/1026
Firefox Share is not available anymore in any ESR/release versions of Firefox
=> remove firefox share documentation

index.php
Recommended method for PHP >= 5.4.0 as seen here https://stackoverflow.com/questions/6249707/check-if-php-session-has-already-started
Per https://shaarli.readthedocs.io/en/master/Server-configuration/ Shaarli supports PHP >= 5.6
=> Update session start condition

tpl/default/addlink.html
Don't use placeholder instead of label for form input.
=> add label to form - accessibility issue

.travis.yml
Fixed non escaped `-` in regex. 
Requires shaarli/netscape-bookmark-parser#46 to be merged and release to get this one green.
=>  Run Shaarli's tests against PHP 7.3 RC1 on Travis 

application/security/LoginManager.php, tests/security/LoginManagerTest.php
This allows the user to stay logged in if his IP changes.
Fixes #1106 
Note: this setting labelled « Disabled protection » can obviously become a security issue.
=> Do not check the IP address with session protection disabled

assets/default/scss/shaarli.scss
to 
EDIT: it's not perfect but the width depends on the size of the icon.
=> Fix button overlapping on mobile in linklist

application/bookmark/LinkDB.php, index.php
- initiate its status to false when the link is created
- if not defined, initiate its status to false (can happen if the updater hasn't run)
=> Fix a warning if links sticky status isn't set

doc/md/Server-configuration.md
=> Documentation: drop PHP 7.0 compatibility in Shaarli 11.x

.readthedocs.yml
workaround for mkdocs incompatibility with python 3.7
Readthedocs builds were failing for some time
https://github.com/rtfd/readthedocs.org/issues/5250
Build success: https://readthedocs.org/api/v2/build/8840127.txt
=> docs: add readthedocs configuration file

assets/default/scss/shaarli.scss
To make it more visible in the middle of raw text.
=> Slightly lighten visited link color

assets/default/scss/shaarli.scss, tpl/default/linklist.html
Fixes #1291
* Display the header bar only on the first page
* Hide search bars, pagination buttons, filters, and edit/delete buttons
=> Add print CSS rules to the default template

application/security/BanManager.php, application/security/LoginManager.php, doc/md/Server-configuration.md, index.php, tests/security/BanManagerTest.php, tests/security/LoginManagerTest.php
This adds a dedicated manager class to handle all ban interactions, which is instantiated and handled by LoginManager.
IPs are now stored in the same format as the datastore, through FileUtils.
Fixes #1032 #587
=> Rewrite IP ban management

Dockerfile.armhf
Building the docker image from Dockerfile.armhf (on Rasperrby PI 3B+) outputs the following error:
```
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for pubsubhubbub/publisher dev-master -> satisfiable by pubsubhubbub/publisher[dev-master].
- pubsubhubbub/publisher dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.
To enable extensions, verify that they are enabled in your .ini files:
- /etc/php7/php.ini
- /etc/php7/conf.d/00_iconv.ini
- /etc/php7/conf.d/00_json.ini
- /etc/php7/conf.d/00_mbstring.ini
- /etc/php7/conf.d/00_openssl.ini
- /etc/php7/conf.d/01_phar.ini
You can also run `php …
```
=> Building Docker image for armhf outputs error

application/bookmark/LinkUtils.php, application/config/ConfigManager.php, doc/md/Shaarli-configuration.md, inc/languages/fr/LC_MESSAGES/shaarli.po, index.php, tests/bookmark/LinkUtilsTest.php, tpl/default/configure.html, tpl/vintage/configure.html
If the option is enabled, it will try to find a meta tag containing the page description and keywords, just like we do for the page title. It will either look for regular meta tag or OpenGraph ones.
The option is disabled by default.
Note that keywords meta tags is mostly not used.
In `configure` template, the variable associated with this setting is `$retrieve_description`.
Fixes #1302
=> Automatically retrieve description for new bookmarks

tpl/default/loginform.html
Don't use tabindex values other than -1, 0. (see https://webaim.org/techniques/keyboard/tabindex).
Fix inputs without labels (the placeholder attribute is not a proper labelling method)
=> a11y fix: label and tabindex

index.php
=> Persist sticky status on bookmark update

Dockerfile
I'm not exactly sure what was going but the `master` branch hasn't build on docker hub in ~3 months due to an issue with `node-sass`:
```
error An unexpected error occurred: "/shaarli/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /shaarli/node_modules/node-sass
Output:
Building: /usr/local/bin/node /shaarli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/shaarli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli …
```
=> Docker: Bump NodeJS version to prevent an issue with node-sass

.travis.yml
=> Remove Travis unit tests against PHP 5.6 and 7.0

index.php
This PR fixes a notice that appear on daily page when at least one link has no thumbnail:
```html
<br />
<b>Notice</b>:  Undefined index: thumbnail in <b>F:\Dev\PHP\shaarli\index.php</b> on line <b>468</b><br />
<!DOCTYPE html>
```
It's invisible with the default theme but visible in the HTML itself.
=> Fixes a Undefined index: thumbnail in daily page.

application/bookmark/LinkDB.php, tests/bookmark/LinkDBTest.php
If timestamps are equals, we sort bookmarks by ID.
Note that bookmarks are reorder when the datastore is saved.
Fixes #1348
=> Make sure that bookmark sort is consistent, even with equal timestamps

tpl/default/feed.atom.html, tpl/vintage/feed.atom.html
Related FreshRSS/FreshRSS#2466
=> ATOM Feed: use instance name as author name instead of URL

tests/bookmark/LinkDBTest.php
Otherwise the datastore is empty in the last test, making it
inconsistent due to dates issues.
=> Fix UT: LinkDBTest - make each tests independant

assets/default/scss/shaarli.scss
For some reason, bLazy won't load the image if the img block has either 0 height or width.
I'm not sure what changed, but lazy loading didn't work anymore:
* Chromium 76: both linklist and picwall
* Firefox 68: picwall
=> Fix image lazy loading issues

plugins/markdown/markdown.php, tests/plugins/PluginMarkdownTest.php
The plugin was only reversing permalinks and failed with setting `rss_permalinks` set to false.
=> Markdown plugin: fix RSS feed direct link reverse

application/feed/FeedBuilder.php
Adds another line break before inserting RSS permalink to avoid including it in markdown blocs, such as blockquote.
=> Fix RSS permalink included in Markdown bloc

application/Thumbnailer.php
OpenGraph thumbnails are well supported on soundcloud.com, displaying an album/track/artist cover image
=> thumbnailer: add soundcloud.com to list of common media domains

doc/md/Community-&-Related-software.md
Since emojis are in every web browsers now, these plugins have no purpose anymore. And they are very outdated.
=> emojione & twemoji removed

doc/md/Server-configuration.md
Without php-json the installation stops with a white screen and the following error:
> 09-Nov-2019 14:05:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Shaarli\Config\json_encode() in /var/www/html/shaarli/application/config/ConfigJson.php:48
> Stack trace:
> #0 /var/www/html/shaarli/application/config/ConfigManager.php(239): Shaarli\Config\ConfigJson->write('data/config.jso...', Array)
> #1 /var/www/html/shaarli/index.php(1835): Shaarli\Config\ConfigManager->write(false)
> #2 /var/www/html/shaarli/index.php(178): install(Object(Shaarli\Config\ConfigManager), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager))
> #3 {main}
>   thrown in /var/www/html/shaarli/application/config/ConfigJson.php on line 48
Tested with Shaarli 0.10.4 on CentOS 8 …
=> Add php-json as required PHP module

doc/md/docker/shaarli-images.md
Fix  base image and PHP version used for `stable` version
=> Fix #1382 - update documentation related to docker images

tpl/default/includes.html, tpl/vintage/includes.html
Using the latest `master` branch code, the warning looked like this in my logs:
```
[error] FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: updated in /usr/share/nginx/html/shaarli/tmp/includes.cedf684561d925457130839629000a81.rtpl.php on line 40" while reading response header from upstream
```
=> Avoiding warning 'PHP Notice: Undefined index: updated'

application/bookmark/BookmarkFileService.php, application/formatter/BookmarkDefaultFormatter.php, application/formatter/BookmarkFormatter.php, application/formatter/BookmarkMarkdownFormatter.php, application/formatter/FormatterFactory.php, index.php, tests/bookmark/BookmarkFileServiceTest.php, tests/feed/FeedBuilderTest.php, tests/formatter/BookmarkDefaultFormatterTest.php, tests/formatter/BookmarkMarkdownFormatterTest.php, tests/formatter/BookmarkRawFormatterTest.php, tests/formatter/FormatterFactoryTest.php, tests/netscape/BookmarkExportTest.php
The new bookmark service wasn't handling private tags properly.
nomarkdown tag is now shown only for logged in user in bookmarks, and hidden for everyone in tag clouds/lists.
Fixes #726
=> Fix an issue with private tags and fix nomarkdown tag

Makefile
the syntax {doc,venor} is only supported in bash and make uses /bin/sh as default shell
=> fix directory creation in makefile

index.php
Trying to do will raise a warning since PHP 7.2, and it never worked as intended.
See: https://bugs.php.net/bug.php\?id\=75650
I've noticed this because dev mode now raise exceptions on warnings:
```
PHP Fatal error:  Uncaught ErrorException: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /home/arthur/PhpstormProjects/Shaarli/index.php:248
Stack trace:
#0 [internal function]: {closure}()
#1 /home/arthur/PhpstormProjects/Shaarli/index.php(248): session_set_cookie_params()
#2 {main}
thrown in /home/arthur/PhpstormProjects/Shaarli/index.php on line 248
```
=> Session cookie setting being set while session is active

index.php
It happens if we have a maximum of 1 occurrence in tags (log(1) = 0)
=> Fix division by zero in tagcloud

application/http/UrlUtils.php
This is to allow local link for markdown, actually a local link write with this syntax :
`[anchor](#local_link)`
produce this HTML code:
> http://#local_link
in place of 
> #local_link
=> Add an exception to method 'whitelist_protocols' for url which started with '#'

doc/md/Plugin-System.md
I've tried to create a plugin following the documentation, but it wasn't working. 
Turns out the .meta file is also required. I've modified the documentation accordingly in this PR.
The plugin might be initialized but won't be displayed in the plugin administration if that file is missing. When the plugin administration page is loaded, the plugins metas are fetched:
https://github.com/shaarli/Shaarli/blob/cf01113cad2fc772113b5d1b7cd5be5e712ae0eb/index.php#L1542
If the meta file does not exist, the iterated plugin is simply passed.
https://github.com/shaarli/Shaarli/blob/cf01113cad2fc772113b5d1b7cd5be5e712ae0eb/application/plugin/PluginManager.php#L191-L193
Technically only the file itself is required but, in the docs I've added that the description variable should be present.
=> Improve documentation about how to create and initialize a plugin

application/http/UrlUtils.php, index.php
* on 'daily' page, when the thumbnail option is deactivated, an error occur during PHP parsing for index not exists for $link['thumbnail']
* local link in Markdown render
When a local link is writting in markdown syntax (with markdown render), the link:
`[text](#local_link)`
produce in render:
`<a href="http://#local_link">`
in place of:
`<a href="#local_link">`
=> V0.11 fixes one error on 'daily' page & a malfunction for local link in Markdown render

Dockerfile.armhf
This is to fix this error I got when building to my Raspberry  Pi :
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for slim/slim 3.12.3 -> satisfiable by slim/slim[3.12.3].
- slim/slim 3.12.3 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
To enable extensions, verify that they are enabled in your .ini files:
- /etc/php7/php.ini
- /etc/php7/conf.d/00_curl.ini
- /etc/php7/conf.d/00_iconv.ini
- /etc/php7/conf.d/00_json.ini
- /etc/php7/conf.d/00_mbstring.ini
- /etc/php7/conf.d/00_openssl.ini
- /etc/php7/conf.d/01_phar.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
=> Fix missing php7-simplexml plugin for Dockerfile.armhf

application/security/LoginManager.php, doc/md/Shaarli-configuration.md, tests/security/LoginManagerTest.php
This makes authentication through LDAP possible.
If "`ldap.host`" is defined in config and is not an empty string, then the user is authenticated through LDAP bind.
Otherwise, authentication is local.
=> ldap authentication, fixes shaarli/Shaarli#1343

.travis.yml
This upgrade fixes PHP 7.4 fatal error builds, because dist < xenial do
not include php-gd with PHP 7.4.
=> Travis CI: upgrade distribution and remove deprecated sudo

Dockerfile
Builds have been failing for a while, again.
=> Fix Docker build: gcc is no longer included in python alpine image

application/container/ContainerBuilder.php, application/container/ShaarliContainer.php, application/front/controller/visitor/ShaarliVisitorController.php, application/plugin/PluginManager.php, inc/languages/fr/LC_MESSAGES/shaarli.po, tests/PluginManagerTest.php, tests/container/ContainerBuilderTest.php, tests/plugins/test/test.php
If a PHP is raised while executing plugin hook, Shaarli will display an error instead of rendering the error page (or just ending in fatal error for default hooks).
Also added phpErrorHandler which is handled differently that regular errorHandler by Slim.
=> Better handling of plugin incompatibility

assets/default/js/base.js
This allow users to submit the form multiple times, because there is no actual browser redirection to the page.
Fixes #1532
=> Export: refresh CRSF token after submit

application/legacy/LegacyController.php, tests/legacy/LegacyControllerTest.php
Makes sure that the user is properly redirected to the bookmark form after login, even with legacy routes.
ping @mro
EDIT: added redirection from `?do=configure` in the same PR.
=> Fix support for legacy route login redirection

application/front/ShaarliMiddleware.php
GET /login and POST /login have 2 distinct route name.
Fixes #1533
=> Fix login loop for private instances

application/render/PageBuilder.php, assets/default/scss/shaarli.scss, tpl/default/linklist.paging.html
Hi. I'm creating my own template and noticed there isn't a way to determine the links per page. The issue was first discussed here:
https://github.com/shaarli/Shaarli/issues/173
I added $links_per_page to the RainTpl variables and modified the default template. If the links per page are 20, 50, or 100 the appropriate button is highlighted, otherwise the links per page are displayed in the input text field.
=> Added $links_per_page variable to template and display on default template

plugins/default_colors/default_colors.php, tests/plugins/PluginDefaultColorsTest.php
Current behaviour only generate the custom CSS file when the plugin settings are saved, which can be annoying if the file is deleted but the settings are set.
Most common use case is Docker deployment, because the plugin directory is not mounted as a volume.
=> Default colors plugin: generate CSS file during initialization

application/legacy/LegacyController.php
When a bookmark is post from a logged out user, he is first redirected to the login page with 'returnurl' containing the link, then redirected again when the login is processed.
We need to reencode the posted URL, otherwise the browser does not handle the fragment as a part of the posted parameter.
=> Fix: encoding in legacy route login redirection to post bookmark

plugins/qrcode/qrcode.php
This PR fixes individual shaare pages (e.g., `/shaare/o3Fv-w`) as the relative path is no longer working:
=> Fix broken css/js files on individual shaare pages

application/front/controller/admin/PluginsController.php, application/plugin/PluginManager.php, tests/PluginManagerTest.php, tests/front/controller/admin/PluginsControllerTest.php, tests/plugins/test/test.php
Also prevent the token to be saved.
Fixes #1550
=> Plugins: do not save metadata along plugin parameters

application/container/ContainerBuilder.php, application/container/ShaarliContainer.php, application/front/controller/visitor/ErrorNotFoundController.php, tests/container/ContainerBuilderTest.php, tests/front/controller/visitor/ErrorNotFoundControllerTest.php, tests/front/controller/visitor/FrontControllerMockHelper.php
Use 404 template instead of default Slim error page if the route is not found.
Fixes #827
=> Properly handle 404 errors

.htaccess
Fixes #1549 
I don't think either the Limit or LimitExcept block is necessary in the .htaccess file. Those are used mainly for limiting requests to specific users logged in via Apache or IP addresses. Apache internally determines which methods are expected by the URL. Having both a Limit and LimitExcept block is redundant, so I removed the Limit block. I added PATCH to the LimitExcept block to fix the issue with synchronizing thumbnails.
=> Add PATCH to the allowed Apache request methods

application/feed/FeedBuilder.php, application/front/controller/visitor/DailyController.php, application/http/HttpUtils.php, doc/md/Shaarli-configuration.md, index.php, tests/feed/FeedBuilderTest.php, tests/front/controller/admin/ExportControllerTest.php, tests/front/controller/admin/ToolsControllerTest.php, tests/front/controller/visitor/DailyControllerTest.php, tests/front/controller/visitor/FrontControllerMockHelper.php, tests/front/controller/visitor/InstallControllerTest.php, tests/front/controller/visitor/OpenSearchControllerTest.php, tests/http/HttpUtils/IndexUrlTest.php, tests/http/HttpUtils/IndexUrlTestWithConstant.php
This new setting under 'general.root_url' allows to override automatic discovery of Shaarli instance's URL.
Fixes #1339
ping @foudfou
EDIT: added to `v0.12.0` milestone because it can be a good workaround in case of regression regarding route discovery.
=> Add manual configuration for root URL

Makefile
static_analysis_summary was removed in 37c9c6b#diff-b67911656ef5d18c4ae36cb6741b7965 but not from the all: target dependencies. Therefore running make all always fails.
fixes https://github.com/shaarli/Shaarli/issues/1459
=> Makefile: remove static_analysis_summary from all: target

Makefile, doc/md/dev/Unit-tests.md
doc/Makefile: remove references to composer update
- add make composer_dependencies_dev Makefile target and use this instead
- fix composer initial installation procedure
- fix php-xdebug install instructions
=> doc/Makefile: remove references to composer update

application/bookmark/LinkUtils.php, application/front/controller/admin/ManageShaareController.php, tests/bookmark/LinkUtilsTest.php
Also fixed the regex to support this failing header: `charset="utf-8"\r\n"`
=> Fix warning if the encoding retrieved from external headers is invalid

.htaccess, application/api/ApiMiddleware.php, tests/api/ApiMiddlewareTest.php
The hoster writes the environment variable with bearer token to
`REDIRECT_HTTP_AUTHORIZATION` and I need to provide `RewriteBase /` to
`.htaccess`
Additionally the JWT workaround does not work:
`RewriteCond %{HTTP:Authorization} ^(.*)`                                                                                                     
`RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`
but
`SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`
helped.
=> Workaround for hoster (ionos)

docker-compose.yml
- fixes https://github.com/shaarli/Shaarli/issues/1493
- https://hub.docker.com/_/traefik/
=> docker-compose.yml: pin traefik image to 1.7-alpine

application/api/ApiUtils.php, application/api/controllers/ApiController.php, application/api/controllers/Links.php, tests/api/controllers/links/PostLinkTest.php
Note that if they're not provided, default behaviour will apply:
creation and update dates will be autogenerated, and not empty.
Fixes #1223
=> REST API: allow override of creation and update dates

application/bookmark/LinkUtils.php, tests/bookmark/LinkUtilsTest.php
Also added a bunch of tests to cover more use cases.
Fixes #1375
(as you can imagine reading the state of the regex, I had a lot of fun working on this :no_mouth:)
=> Improve regex to extract HTML metadata (title, description, etc.)

application/api/ApiMiddleware.php, application/bookmark/BookmarkFileService.php, application/bookmark/BookmarkIO.php, application/bookmark/BookmarkServiceInterface.php, application/container/ContainerBuilder.php, composer.json, composer.lock, init.php, tests/api/controllers/info/InfoTest.php, tests/api/controllers/links/DeleteLinkTest.php, tests/api/controllers/links/GetLinkIdTest.php, tests/api/controllers/links/GetLinksTest.php, tests/api/controllers/links/PostLinkTest.php, tests/api/controllers/links/PutLinkTest.php, tests/api/controllers/tags/DeleteTagTest.php, tests/api/controllers/tags/GetTagNameTest.php, tests/api/controllers/tags/GetTagsTest.php, tests/api/controllers/tags/PutTagTest.php, tests/bookmark/BookmarkFileServiceTest.php, tests/bookmark/BookmarkFilterTest.php, tests/bookmark/BookmarkInitializerTest.php, tests/bootstrap.php, tests/feed/FeedBuilderTest.php, tests/netscape/BookmarkExportTest.php, tests/netscape/BookmarkImportTest.php, tests/updater/UpdaterTest.php
To make sure that there is no concurrent operation on the datastore file.
It uses the library https://github.com/php-lock/lock with `FlockMutex` which relies on the filesystem to perform its lock.
Fixes #1132
=> Add mutex on datastore I/O operations

application/api/ApiUtils.php, application/api/controllers/Links.php, application/bookmark/Bookmark.php, application/bookmark/BookmarkArray.php, application/bookmark/BookmarkFileService.php, application/bookmark/BookmarkFilter.php, application/bookmark/BookmarkIO.php, application/bookmark/BookmarkInitializer.php, application/bookmark/BookmarkServiceInterface.php, application/feed/FeedBuilder.php, application/front/controller/admin/ThumbnailsController.php, application/security/LoginManager.php, tests/HistoryTest.php, tests/bookmark/BookmarkArrayTest.php, tests/bookmark/BookmarkFileServiceTest.php, tests/bookmark/BookmarkTest.php, tests/front/controller/admin/ManageShaareControllerTest/DeleteBookmarkTest.php, tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php, tests/front/controller/admin/ThumbnailsControllerTest.php
Parameters typing and using strict types overall increase the codebase
quality by enforcing the a given parameter will have the expected type.
It also removes the need to unnecessary unit tests checking methods
behavior with invalid input.
=> Add strict types for bookmarks management

application/front/controller/visitor/ShaarliVisitorController.php, application/plugin/PluginManager.php, application/render/PageBuilder.php, doc/md/Server-configuration.md, doc/md/dev/Plugin-system.md, plugins/archiveorg/archiveorg.php, plugins/isso/isso.php, plugins/qrcode/qrcode.php, plugins/wallabag/wallabag.php, tpl/default/daily.html, tpl/default/includes.html, tpl/default/linklist.html, tpl/default/page.footer.html, tpl/default/picwall.html, tpl/default/pluginsadmin.html
- Shaarli can be fully used by prefixing any URL with /index.php/
- {$base_path} used in templates already works with this configuration
- Assets path (outside of theme's assets) must be prefixed with {$root_url}/
- Documentation section in « Server configuration »
Fixes #1590
=> Support using Shaarli without URL rewriting

application/bookmark/Bookmark.php, application/bookmark/BookmarkFilter.php, application/formatter/BookmarkDefaultFormatter.php, application/formatter/BookmarkFormatter.php, application/formatter/BookmarkMarkdownFormatter.php, assets/default/scss/shaarli.scss, tests/api/controllers/links/GetLinksTest.php, tests/bookmark/BookmarkFileServiceTest.php, tests/bookmark/BookmarkFilterTest.php, tests/formatter/BookmarkDefaultFormatterTest.php, tests/legacy/LegacyLinkDBTest.php, tests/utils/ReferenceLinkDB.php, tpl/default/linklist.html
How it works:
1. when a fulltext search is made, Shaarli looks for the first
occurence position of every term matching the search. No change here,
but we store these positions in an array, in Bookmark's additionalContent.
2. when formatting bookmarks (through BookmarkFormatter
implementation):
1. first we insert specific tokens at every search result positions
2. we format the content (escape HTML, apply markdown, etc.)
3. as a last step, we replace our token with displayable span
elements
Cons: this tightens coupling between search filters and formatters
Pros: it was absolutely necessary not to perform the
search twice. this solution has close to no impact on performances.
Fixes #205
=> Feature: highlight fulltext search results 

Makefile, application/config/ConfigManager.php, application/container/ContainerBuilder.php, application/container/ShaarliContainer.php, application/front/controller/admin/ManageShaareController.php, application/front/controller/admin/MetadataController.php, application/http/HttpAccess.php, application/http/HttpUtils.php, application/http/MetadataRetriever.php, assets/common/js/metadata.js, assets/default/js/base.js, assets/default/scss/shaarli.scss, doc/md/Shaarli-configuration.md, index.php, package.json, tests/bookmark/LinkUtilsTest.php, tests/container/ContainerBuilderTest.php, tests/front/controller/admin/ManageShaareControllerTest/DisplayCreateFormTest.php, tests/http/MetadataRetrieverTest.php, tpl/default/editlink.html, webpack.config.js, yarn.lock
- There is a new standalone script (metadata.js) which requests
a new controller to get bookmark metadata and fill the form async
- This feature is enabled with the new setting: general.enable_async_metadata
(enabled by default)
- general.retrieve_description is now enabled by default
- A small rotating loader animation has a been added to bookmark inputs
when metadata is being retrieved (default template)
- Custom JS htmlentities has been removed and  mathiasbynens/he
library is used instead
Fixes #1563
EDIT added:  Improve metadata retrieval (performances and accuracy)
- Use dedicated function to download headers to avoid apply multiple regexps on headers
- Also try to extract title from meta tags
=> Add a setting to retrieve bookmark metadata asynchrounously

application/bookmark/Bookmark.php, application/front/controller/admin/ManageShaareController.php, application/front/controller/visitor/BookmarkListController.php, assets/common/js/metadata.js, tests/bookmark/BookmarkTest.php, tests/front/controller/admin/ManageShaareControllerTest/DisplayCreateFormTest.php, tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php, tests/front/controller/visitor/BookmarkListControllerTest.php, tpl/default/linklist.html, tpl/vintage/linklist.html
This feature is based `general.enable_async_metadata` setting and works with existing metadata.js file.
The script is compatible with any template:
- the thumbnail div bloc must have `data-async-thumbnail` attribute
- the bookmark bloc must have `data-id` attribute with the bookmark ID as value
Fixes #1564
=> Asynchronous retrieval of bookmark's thumbnails 

application/config/ConfigJson.php
i was getting error 
```
An error occurred while parsing JSON configuration file (data/config.json.php): error code #4
➜ Syntax error
Please check your JSON syntax (without PHP comment tags) using a JSON lint tool such as jsonlint.com.
```
after debug i found 
```php
$data = str_replace(self::getPhpHeaders(), '', $data);
$data = str_replace(self::getPhpSuffix(), '', $data);
```
doesn't removing php header and php suffix
cause of this issue was PHP_EOL represents the endline character for the current system. if my  ```config.json.php```  was encoded with unix ( LF ) and php running on windows windows encoding ( CR LF ) is not same as unix encoding ( LF ) so ```str_replace``` doesn't replace strin  then it causes issue.
=> Removed PHP_EOL in configuration file

application/ApplicationUtils.php, application/FileUtils.php, application/front/controller/admin/ServerController.php, application/front/controller/visitor/BookmarkListController.php, application/front/controller/visitor/InstallController.php, assets/default/scss/shaarli.scss, inc/languages/fr/LC_MESSAGES/shaarli.po, index.php, tests/ApplicationUtilsTest.php, tests/FileUtilsTest.php, tests/front/controller/admin/ServerControllerTest.php, tests/front/controller/visitor/InstallControllerTest.php, tpl/default/install.html, tpl/default/server.html, tpl/default/server.requirements.html, tpl/default/tools.html
It contains mostly read only information about the current Shaarli instance,
PHP version, extensions, file and folder permissions, etc.
Also action buttons to clear the cache or sync thumbnails.
Part of the content of this page is also displayed on the install page,
to check server requirement before installing Shaarli config file.
Fixes #40
Fixes #185
There are 2 new optional templates: 
- server.html
- server.requirements.html
Screenshots (one with errors set manually in the code):
=> Feature: add a Server administration page

application/bookmark/BookmarkFileService.php, application/bookmark/BookmarkServiceInterface.php, application/front/controller/admin/ManageShaareController.php, application/front/controller/visitor/BookmarkListController.php, inc/languages/fr/LC_MESSAGES/shaarli.po, index.php, tests/bookmark/BookmarkFileServiceTest.php, tests/front/controller/admin/ManageShaareControllerTest/SharePrivateTest.php, tests/front/controller/visitor/BookmarkListControllerTest.php, tpl/default/linklist.html
- Add a share link next to « Permalink » in linklist (using share icon
from fork awesome)
- This link generates a private key associated to the bookmark
- Accessing the bookmark while logged out with the proper key will
display it
Fixes #475
=> Feature: Share private bookmarks using a URL containing a private key

Dockerfile
Composer 2.0 is now blocking everything if requirements are not met
=> Include php-simplexml in Docker image

application/api/controllers/Links.php, tests/api/controllers/links/PostLinkTest.php
Hey guys,
I got numerous report on Shaarlier that the app erroneous thinks that links are not correctly posted, even if they were. This happens in the case if Shaarli is not located at the root domain, which is a common use case: `my.domain.com/shaarli/`.
On posting a new link, the API would return a `Location: api/link/<link_id>` header that is incorrect in this scenario. I've made the necessary changes here to always return an absolute path.
This is an important, but non critical bug, since no data is lost.
Let me know if there are anything I should do for this PR to be accepted.
Thank you!
=> API postLink: change relative path to absolute path

application/front/controller/admin/ShaareManageController.php, tests/front/controller/admin/ShaareManageControllerTest/DeleteBookmarkTest.php
Except if the referer points to a permalink (which has been deleted).
Fixes #1622
=> Fix: redirect to referrer after bookmark deletion

application/front/controller/visitor/ErrorController.php, assets/default/scss/shaarli.scss, inc/languages/fr/LC_MESSAGES/shaarli.po, tests/front/controller/visitor/ErrorControllerTest.php, tpl/default/error.html
It makes more sense to display the error even if it's unexpected.
Only for logged in users.
Fixes #1606
=> Display error details even with dev.debug set to false

application/bookmark/LinkUtils.php, tests/bookmark/LinkUtilsTest.php
Previous regex forced the selection to stop at either the first single or double quote found, regardless of the opening quote. Using '\1', we're sure to wait for the proper quote before stopping the capture.
=> Fix an issue truncating extracted metadata content

.docker/nginx.conf, .dockerignore, doc/md/Server-configuration.md
Both in documentation and Docker image.
For security purpose, it no longer allow to access static files through
the main nginx *location*. Static files are served if their extension
matches the whitelist.
As a side effect, we no longer need specific restrictions, and
therefore it fixes the nginx part of #1608.
=> Reviewed nginx configuration

doc/md/Docker.md, docker-compose.yml
Use envvar SHAARLI_VIRTUAL_HOST for Traefik's docker.domain parameter instead of localhost (I'm not sure if did work at some point).
Add an environment variable to choose which Docker tag to use instead of using master by default.
Fixes #1632
(EDIT: tested on a fresh EC2 instance)
=> Docker-compose: fix SSL certificate + add parameter for Docker tag

.htaccess, doc/md/Server-configuration.md
(in documentation)
For security purpose, block access to any static file not matching the list of allowed extensions.
It allows us to remove the specific restriction on dotfiles, and fix Apache part of #1608.
Tested with AWS build of HTTPD: Apache/2.4.46.
I'm not super confident in my Apache config skills, so if you have some time to test it @nodiscc, @kcaran, or anyone running an Apache instance, it would be greatly appreciated:
- every assets should load properly, including custom `data/user.css`
- other static files such as `README.md`, `yarn.lock`, `data/log.txt`, etc. should not be accessible.
- searching for private tags (starting with a dot) should work properly.
=> Reviewed Apache configuration

application/config/ConfigManager.php, application/front/controller/admin/ServerController.php, inc/languages/fr/LC_MESSAGES/shaarli.po
If the setting 'updates.check_updates' is disabled, do not retrieve the latest version on server administration page.
Additionally, updated default values for
- updates.check_updates from false to true
- updates.check_updates_branch from stable to latest
=> Server admin: do not retrieve latest version without update_check

Dockerfile.armhf
The Docker for armhf doesn't build anymore on Alpine 3.8, upgrading to 3.10.
Building works fine on a Rapsberry Pi 4 running Raspbian GNU/Linux 10 (buster)
This is the error with 3.8:
```
[2/4] Fetching packages...
error css-loader@4.3.0: The engine "node" is incompatible with this module. Expected version ">= 10.13.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c apk --update --no-cache add yarn nodejs-current python2 build-base     && cd /shaarli     && yarn install     && yarn run build     && rm -rf node_modules' returned a non-zero code: 1
```
Not upgrading to 3.11, due to this error:
```
2/4] Fetching packages...
error browserslist@4.14.3: The engine "node" is incompatible with this …
```
=> Upgrade alpine from 3.8 to 3.10 in armhf Dockerfile

application/container/ContainerBuilder.php, application/plugin/PluginManager.php, application/plugin/exception/PluginInvalidRouteException.php, doc/md/dev/Plugin-system.md, index.php, phpcs.xml, plugins/demo_plugin/DemoPluginController.php, plugins/demo_plugin/demo_plugin.php, tests/PluginManagerTest.php, tests/container/ContainerBuilderTest.php, tests/plugins/test/test.php, tests/plugins/test_route_invalid/test_route_invalid.php, tpl/default/pluginscontent.html
- each route will be prefixed by `/plugin/<plugin_name>`
- add a new template for plugins rendering
- add a live example in the demo_plugin
Check out the "Plugin System" documentation for more detail.
Related to #143
=> Plugin system: allow plugins to provide custom routes

application/front/controller/visitor/DailyController.php, application/helper/DailyPageHelper.php, tests/helper/DailyPageHelperTest.php
It is not useful for the RSS feed, as every new entry will be marked as 'yesterday', and requires an update the next day.
=> Daily RSS - Remove relative description (today, yesterday)

application/feed/CachedPage.php, application/front/controller/visitor/DailyController.php, application/helper/DailyPageHelper.php, application/render/PageCacheManager.php, tests/feed/CachedPageTest.php, tests/helper/DailyPageHelperTest.php
Currently the cache is only invalidated when the datastore changes, while it should rely on selected period of time.
Fixes #1659
=> Daily RSS Cache: invalidate cache base on the date

application/front/controller/admin/ShaarePublishController.php, application/http/MetadataRetriever.php, tests/http/MetadataRetrieverTest.php
Metadata can now only be string or null.
Fixes #1653
=> Fix: synchronous metadata retrieval is failing in strict mode

application/api/ApiUtils.php, application/api/controllers/Links.php, tests/api/controllers/links/PostLinkTest.php, tests/api/controllers/links/PutLinkTest.php
Even though the documentation specify that tags should be passed as an array, tags string is actually allowed in the code. So this adds a proper parsing with configured separator.
Related to #1651
=> API: POST/PUT Link - properly parse tags string

application/front/controller/visitor/ShaarliVisitorController.php, tests/front/controller/visitor/ShaarliVisitorControllerTest.php
Use either legacy key `_PAGE_` or new `template` one.
Related to https://github.com/kalvn/Shaarli-Material/issues/118
=> Inject current template name in templates

assets/common/js/shaare-batch.js
Use 'checked' attribute instead of 'value' for checkboxes. 'value' always returns 'on'.
Fixes #1684
=> Fix: bulk add - private status

application/front/controller/admin/ShaareManageController.php, assets/common/js/shaare-batch.js, tests/front/controller/admin/ShaareManageControllerTest/DeleteBookmarkTest.php
Do not send redirect response in bookmark delete controller if the request comes from bulk creation page.
Fixes #1683
=> Fix: bulk add - delete existing link

assets/common/js/shaare-batch.js
Otherwise cookie may not be store under the right subfolder, thus generating tokens in the wrong session file.
Fixes #1690
=> Fix: bulk add redirection with ending slash

application/bookmark/LinkUtils.php, application/formatter/BookmarkDefaultFormatter.php, application/formatter/BookmarkMarkdownExtraFormatter.php, application/formatter/BookmarkMarkdownFormatter.php, application/formatter/Parsedown/ShaarliParsedown.php, application/formatter/Parsedown/ShaarliParsedownExtra.php, application/formatter/Parsedown/ShaarliParsedownTrait.php, application/front/controller/visitor/BookmarkListController.php, tests/formatter/BookmarkDefaultFormatterTest.php, tests/formatter/BookmarkMarkdownFormatterTest.php
DefaultFormatter:
- format 'a' tag content and not href attribute
- format hashtags properly
Markdown(Extra)Formatter:
- Extend Parsedown to format highlight properly: https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions
Fixes #1681
@nodiscc @virtadpt If you could give it a try that would be nice :)
=> Support search highlights when matching URL content

application/api/ApiMiddleware.php, application/bookmark/BookmarkFileService.php, application/bookmark/BookmarkFilter.php, application/container/ContainerBuilder.php, application/plugin/PluginManager.php, doc/md/dev/Plugin-system.md, plugins/demo_plugin/demo_plugin.php, tests/PluginManagerTest.php, tests/api/ApiMiddlewareTest.php, tests/api/controllers/info/InfoTest.php, tests/api/controllers/links/DeleteLinkTest.php, tests/api/controllers/links/GetLinkIdTest.php, tests/api/controllers/links/GetLinksTest.php, tests/api/controllers/links/PostLinkTest.php, tests/api/controllers/links/PutLinkTest.php, tests/api/controllers/tags/DeleteTagTest.php, tests/api/controllers/tags/GetTagNameTest.php, tests/api/controllers/tags/GetTagsTest.php, tests/api/controllers/tags/PutTagTest.php, tests/bookmark/BookmarkFileServiceTest.php, tests/bookmark/BookmarkFilterTest.php, tests/bookmark/BookmarkInitializerTest.php, tests/feed/FeedBuilderTest.php, tests/netscape/BookmarkExportTest.php, tests/netscape/BookmarkImportTest.php, tests/plugins/test/test.php, tests/updater/UpdaterTest.php
A new plugin hook has been added: hook_test_filter_search_entry
This hook allows to filter out bookmark with custom plugin code when a search is performed.
Related to #143
=> New plugin hook: ability to add custom filters to Shaarli search engine

doc/md/Server-configuration.md
WIthout this directive apache will try other default/global DirectoryIndex files resulting in useless file access/error messages in logs
```
[Sun Mar 07 14:04:25.383960 2021] [authz_core:error] [pid 946:tid 139985284290304] [client 10.0.0.1:42616] AH01630: client denied by server configuration: /var/www/links.example.org/index.html
[Sun Mar 07 14:04:25.384293 2021] [authz_core:error] [pid 946:tid 139985284290304] [client 10.0.0.1:42616] AH01630: client denied by server configuration: /var/www/links.example.org/index.cgi
[Sun Mar 07 14:04:25.384465 2021] [authz_core:error] [pid 946:tid 139985284290304] [client 10.0.0.1:42616] AH01630: client denied by server configuration: /var/www/links.example.org/index.pl
```
=> doc: apache: explicitly set index.php as DirectoryIndex

application/bookmark/BookmarkFileService.php
When we try to access the atom feed and have no bookmarks, it raised the following exception :
```
Call to a member function reorder() on array /webroot/application/bookmark/BookmarkFileService.php:143
#0 /webroot/application/feed/FeedBuilder.php(106): Shaarli\Bookmark\BookmarkFileService->search(Array, 'public', false, false, true)
#1 /webroot/application/front/controller/visitor/FeedController.php(47): Shaarli\Feed\FeedBuilder->buildData('atom', Array)
#2 /webroot/application/front/controller/visitor/FeedController.php(20): Shaarli\Front\Controller\Visitor\FeedController->processRequest('atom', Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: Shaarli\Front\Controller\Visitor\FeedController->atom(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) …
```
=> Fix a crash when generating an atom feed with no bookmarks

application/formatter/BookmarkDefaultFormatter.php
It messes with Markdown syntax (tables in this case).
Fixes #1729
=> Search highlight: do not use special characters for tokens

doc/custom_theme/main.html, mkdocs.yml
- pages parameters has been deprecated and renamed by nav
- the build fails with an empty extra_css array
=> Fix documentation build

inc/languages/de/LC_MESSAGES/shaarli.po
I'd recommend to change the German translation. The word "Zeichen" is misleading in this case. It means something like string or character. The word "Token" fits better. In general I'd change the message to "Wrong XSRF token". This makes it more clear what happens here.
=> Change Zeichen to Token

.dockerignore, .github/workflows/docker-latest.yml, .github/workflows/docker-tags.yml, CHANGELOG.md, README.md, doc/md/Docker.md, doc/md/dev/Development.md
- push images to https://hub.docker.com/r/shaarli/shaarli/tags using a personal access token (access tokens are not available for organizations)
- push an image tagged `:latest` for builds on `master`
- push an image with the same tag as the git tag for `v*.*.*` tags, and for the `release` branch
- update documentation (remove references to Travis/Drone CI
- deprecate stable and master Docker tags (ref. https://github.com/shaarli/Shaarli/issues/1453)
- add deprecation notices to CHANGELOG.md
- fixes https://github.com/shaarli/Shaarli/issues/1762
_Tested and working on https://github.com/nodiscc/Shaarli/actions before I removed the `DOCKERHUB_USERNAME/TOKEN` secrets to prevent accidentally pushing to the shaarli/shaarli registry. I entered my own Personal Access token in …
=> build and push docker images using Github Actions

doc/md/Plugins.md
The plugin is now part of core since v0.12.0
=> doc: remove the markdown plugin from the plugins list

tpl/default/feed.atom.html, tpl/default/feed.rss.html
The hub link variable is wrong in default template (this correction) but OK in the vintage one.
=> Correction: pubsubhubbub hub link in RSS / Atom.

.gitignore, application/Utils.php, application/helper/DailyPageHelper.php, tests/bootstrap.php, tests/front/controller/visitor/DailyControllerTest.php, tests/helper/DailyPageHelperTest.php, tests/languages/de/UtilsDeTest.php, tests/languages/en/UtilsEnTest.php, tests/languages/fr/UtilsFrTest.php
This fixes #1844 the issue with the "Monthly Shaarli" previous month link. I also noticed that the strftime function is deprecated in PHP 8.1, so I converted it to DateTime->format(). I also updated the unit tests, and they all pass on PHP 8.1.
Thank you for Shaarli and I'm really excited for the opportunity to help out. Please let me know if I need to do anything more.
=> #1844 - Month end issues with the Daily Shaarli, updates to date processing

.github/workflows/ci.yml, Dockerfile, Dockerfile.armhf, Makefile
- yarnpkg is always aliased to the proper yarn binary on all distributions
- yarn command does not always point to yarn package managed (Debian)
=> build: use the yarnpkg command instead of yarn

Dockerfile, Dockerfile.armhf, doc/md/dev/Unit-tests.md, tests/docker/alpine316/Dockerfile
- https://hub.docker.com/_/alpine
- https://hub.docker.com/r/arm32v6/alpine/
- related https://github.com/shaarli/Shaarli/issues/1757
- related https://github.com/shaarli/Shaarli/issues/1855
=> Dockerfile/Dockerfile.armhf: update base alpine image to v3.16

composer.lock
Especially for latest [slim/slim](https://github.com/slimphp/Slim/releases/tag/3.12.4) and [gettext/gettext](https://github.com/php-gettext/Gettext/blob/v4.8.7/CHANGELOG.md) minor version which fix PHP 8.1 warnings.
=> chore: bump minor composer dependencies

application/front/controller/admin/ShaarliAdminController.php, application/security/SessionManager.php, doc/md/Backup-and-restore.md, doc/md/dev/Development.md, doc/md/dev/Unit-tests.md, plugins/wallabag/wallabag.php, tpl/default/configure.html, tpl/default/install.html, tpl/default/pluginsadmin.html, tpl/default/tools.html
fixes typo, plural form (unfortunately, this is not completed by `t()`), i18n.
=> trivial refine for messages

application/front/controller/visitor/InstallController.php, tests/front/controller/visitor/InstallControllerTest.php
The actual title is not localized, but the /install page shows it as localized.
I propose change it into pure, because a domain name is lengthy and may leak privacy while a screenshot or behind reverse proxy.
=> Simple and uniform localized website title

application/bookmark/Bookmark.php, application/bookmark/BookmarkFilter.php, application/formatter/BookmarkDefaultFormatter.php, application/formatter/BookmarkFormatter.php, application/front/controller/admin/ShaareManageController.php, application/plugin/PluginManager.php, composer.json, doc/md/Plugins.md, plugins/readitlater/ReadItLaterController.php, plugins/readitlater/readitlater.default.css, plugins/readitlater/readitlater.default.js, plugins/readitlater/readitlater.meta, plugins/readitlater/readitlater.php, plugins/readitlater/readitlater_button.html, plugins/readitlater/readitlater_editlink.html, tests/bookmark/BookmarkFileServiceTest.php, tests/formatter/BookmarkDefaultFormatterTest.php, tests/formatter/BookmarkMarkdownFormatterTest.php, tests/front/controller/admin/ShaareManageControllerTest/SharePrivateTest.php, tests/plugins/PluginReadItLaterTest.php, tests/plugins/test_route_invalid/test_route_invalid.php
Create a new core plugin allowing to mark bookmarks to read them later.
When enabled:
* a checkbox is displayed in editlink view for new bookmarks
* a plugin setting is available to check it or not by default
* in bookmarks list:
* new global filter to display only bookmark flagged as read it
later
* for each bookmarks, new action icon to toggle read it later status
* for each « readitlater » bookmark, red label « To Read » added,
and red line on the right of the bookmark added (default template)
Fixes #143
Note that it will probably require some CSS/icon adaption for 3rd party themes, but it's working.
---
This also fixes and gives an example of how to save extra data within bookmarks - fixes #1646.
--- 
UI opinions would be appreciated: ping @nodiscc @kalvn @nicolasdanelon …
=> New Core Plugin: ReadItLater

application/netscape/NetscapeBookmarkUtils.php, composer.json, composer.lock
Apply breaking changes of the new version:
- parsed bookmarks have different field names
- default values (private and tags) are no longer handled by the library
- constructor signature has been updated
=> Netscape bookmark parser: bump to new major version

tpl/default/export.bookmarks.html, tpl/vintage/export.bookmarks.html
- When a bookmark's update date is set, set the `LAST_MODIFIED` attribute
- Ensure the `PRIVATE` attribute contains an integer value
Default bookmarks exported from the current `master` version (extract with `<DT><A>` elements):
```xml
<DT><A HREF="/shaare/f6PbvA" ADD_DATE="1654256014" PRIVATE="" TAGS="shaarli,help">Shaarli - The personal, minimalist, super-fast, database free, bookmarking service</A>
<DT><A HREF="/shaare/poWYsQ" ADD_DATE="1654256014" PRIVATE="1" TAGS="shaarli,help">Note: Shaare descriptions</A>
<DT><A HREF="https://www.youtube.com/watch?v=DVEUcbPkb-c" ADD_DATE="1654256014" PRIVATE="1" TAGS="shaarli,help,thumbnail">Calm Jazz Music - YouTube (private bookmark with thumbnail demo)</A>
```
Default bookmarks exported from the PR branch (extract with `<DT><A>` elements): …
=> Improve bookmark metadata formatting for Netscape exports

.docker/services.d/php-fpm/run, Dockerfile, Dockerfile.armhf, Makefile, tests/docker/alpine316/Dockerfile
- fixes https://github.com/shaarli/Shaarli/issues/1868
- tested successful build with `docker build .`
- did not test building the armhf image due to https://github.com/shaarli/Shaarli/issues/1048
- did not test deploying/running the updated image, Docker users please test
=> update docker images to use PHP 8

Makefile
The syntax was invalid and this target was not actually doing anything (it probably worked at some point in another context).
This change make sure that the .mo files are properly generated, even in unit tests context and fixes #1893
=> Fix translate Makefile target

doc/md/Server-configuration.md
Explicitly allow access to doc folder and HTML files with apache2 documented default configuration.
Fixes #1819 
(tried in local Docker Debian build)
=> doc(apache2): allow access to local docs folder

inc/languages/de/LC_MESSAGES/shaarli.po
"Shaare" is used as a verb and as a noun. In the "shaare"/"shaares"-Keys this was mixed up. The Share term *is* used in the Translation. So there is no need to work around it.
=> Fix mishandling of Shaare term

index.php
One parameter has been removed from set_error_handler. 
Also, there is a warning triggered on every page with a Pimple incompatibility.
=> Fix PHP 8 incompatibility with debug mode enabled

application/bookmark/BookmarkIO.php, application/bookmark/exception/InvalidWritableDataException.php, application/bookmark/exception/NotEnoughSpaceException.php
On every disk write operation, we check the available free disk space (+ slight marging of arbitrary 500kB), and if there is not enough space we do not attempt to write anything.
This should prevent most case of corrupted datastore becoming an empty file due to full HDD.
Fixes #1810
=> Add an additional free disk space check before saving the datastore

plugins/pubsubhubbub/pubsubhubbub.php
On bulk operations, this plugin heavily impacts performances because it make 1 external request
per link saved. Add a simple limit to only make one call per request.
=> PubSubHub Plugin: make 1 external call per request

application/bookmark/Bookmark.php, application/front/controller/admin/ShaareManageController.php, assets/default/js/base.js, index.php, tests/front/controller/admin/ShaareManageControllerTest/AddOrDeleteTagTest.php, tpl/default/page.header.html
This PR adds a new endpoint allowing to add or delete one or multiple tags on one or multiple bookmarks from the front end.
It is only implemented on the default template.
A few screenshots:
- Select one or multiple 
- Add tag(s)
- Delete tag(s)
- 
Fixes #1160 
Fixes #1901
=> Bulk action: add or delete tag to multiple bookmarks

plugins/readitlater/readitlater.php, plugins/readitlater/readitlater_editlink.html, tests/plugins/PluginReadItLaterTest.php
Adds a random string to the HTML ID so it can be unique in batch more, where there are multiple checkboxes in the same form.
=> Fix ReadItLater checkbox label on bulk add

application/bookmark/Bookmark.php, tests/bookmark/BookmarkTest.php
I didn't see any issues relating to this, but shouldn't tags be unique? The new feature to bulk add tags is great, but I don't want to accidently add a tag twice if I select a shaare that already includes the tag.
=> Ensure tags are unique when adding and deleting them from bookmarks.

CHANGELOG.md
"Theming" was not a first-level list item, which made its children display as children of the previous first-level item ("Rest API v1")
=> Fix formatting of v0.9.0 changelog

assets/default/scss/shaarli.scss
#1932 - This fixes the Roboto-Regular and Roboto-Bold @font-family declarations for the default theme when the user has the Roboto family installed locally.
=> 1932: Fixed Roboto-Regular and Roboto-Bold font declarations

.github/workflows/docker-latest.yml, .github/workflows/docker-tags.yml
it's good to have multiple container registries, in case one decides to not be welcoming anymore to open-source projects
=> ci: push container images to github registry in addition to dockerhub

.github/workflows/docker-latest.yml
- fixes https://github.com/shaarli/Shaarli/issues/1676
- second commit reverts changes used for testing/verifying the version string replacement
- testing was successful using `docker run --entrypoint /bin/cat nodiscc/shaarli:latest shaarli/shaarli_version.php` (returns `<?php /* c4a5ef5 */ ?>`)
=> docker: latest: replace dev in shaarli_version.php with the latest commit hash

README.md, doc/md/Docker.md, doc/md/dev/Development.md, docker-compose.yml
- dockerhub free team accounts will be deleted in < 30 days (https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), this affects the Shaarli team account
- automated builds will keep pushing latest builds to dockerhub in addition to gchr.io, until the account is deleted
- **users relying on `shaarli/shaarli` OCI images are advised to migrate to `ghcr.io/shaarli/shaarli` as soon as possible**
- existing tagged images have been copied from https://hub.docker.com/r/shaarli/shaarli/ to https://github.com/shaarli/Shaarli/pkgs/container/shaarli/versions?filters%5Bversion_type%5D=tagged
- prepend `ghcr.io/` to all references to OCI images
- update all references to dockerhub -> github packages registry, update developer documentation, cleanup …
=> doc: move OCI images hosting to ghcr.io

init.php
There are a bunch of deprecation warnings that seem to be displayed by default.
They are still displayed in debug mode.
Related to #1935
=> Do not display deprecated warnings by default

application/bookmark/LinkUtils.php, tests/bookmark/LinkUtilsTest.php
Also in case of any other regex error, just return an empty array instead of a fatal error.
Fixes #1944
=> Fix a bug when using '/' as a tag separator

index.php
If the log file is not writable, create a LoggerInterface instance writing in php://temp instead of getting the library to throw an exception and land in a fatal error. In case of a new installation, the permission issue will be displayed along with the server requirements.
Fixes #1904
=> Fix Logger exception: gracefully handle permission issue

Makefile, doc/md/dev/Release-Shaarli.md
It's not possible to have a make target with the same name as an existing file in the folder.
https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date
And there is an `AUTHORS` file, which conflicts if the file system is not case-sensitive (e.g. default mode of APFS).
=> Rename authors makefile target to avoid conflicts with filename

Makefile, doc/md/dev/Release-Shaarli.md
On MacOS, default tar installation is BSD tar which does not support `--transform` flag used in our Makefile.
=> Makefile: Use GNU tar if available

application/front/controller/admin/ServerController.php, application/legacy/LegacyUpdater.php, doc/md/dev/Release-Shaarli.md
- ref. https://github.com/shaarli/Shaarli/pull/1959
=> doc: update release procedure (merge the latest release to the release branch) + use the release branch for latest release version detection

application/bookmark/BookmarkIO.php
Some shared hosting providers are disabling this function.
Fixes #1968
=> Support: ignore disk_free_space if the function is unavailable

.github/workflows/docker-latest.yml, Makefile
- run trivy from makefile so that it can be run both locally and through github actions
- usage: `make test_trivy TRIVY_TARGET_DOCKER_IMAGE=regist.ry/user/image:tag`
- tested by downgrading the base image to alpine 3.15.7 and verifying that vulnerabilities are reported (https://github.com/nodiscc/Shaarli/actions/runs/4860040980/jobs/8663400103)
- ref. https://github.com/shaarli/Shaarli/issues/1531
=> tools: run trivy vulnerability scanner on the 'latest' docker image

.github/workflows/docker-latest.yml
- fixes Error response from daemon: no such image: ghcr.io/***:trivy: No such image: ghcr.io/***:trivy
- introduced in https://github.com/shaarli/Shaarli/pull/1980 but the test target branch/tag was never reverted to 'latest'
=> gihub actions: fix value of TRIVY_TARGET_DOCKER_IMAGE

.docker/nginx.conf
A very small patch to have Shaarli's container nginx listen on IPv6 addresses as well as IPv4 addresses; this lets it run happily on IPv6-native clusters/networks/etc. and shouldn't impair IPv4 usage.
A test container (that I'm running now) is available at _cerebrate/shaarli:v6test_ .
=> docker: nginx: listen on IPv6 in addition to IPv4

application/api/controllers/Info.php
Expose the value of the configured tags_separator through the /info API endpoint.
This value can be used by clients (such as Shaarlier, see issue [#55 on Shaarlier](https://github.com/dimtion/Shaarlier/issues/55#)) for consistency.
=> Expose tags_separator config through /info API

.github/workflows/ci.yml, .github/workflows/docker-latest.yml, .gitignore, Makefile
- run scan on each push/pull request update
- can be run locally using make test_trivy_repo
- exit with error code 0/success when vulnerabilities are found,  as not to make the workflow fail, a separate periodic run that exits with code 1 should be added in parallel
- update trivy to v0.43.0 (https://github.com/aquasecurity/trivy/releases/tag/v0.43.0)
- also consider TRIVY_EXIT_CODE when running trivy on the latest docker image
- ref. https://github.com/shaarli/Shaarli/issues/1531
---------
This is reproduces functionality provided by Github's [dependabot alerts](https://github.com/shaarli/Shaarli/security/dependabot), but with the ability to run locally/more portable, and reuses an already existing tool (`trivy` can run on `yarn/composer.lock` as well as Docker images). In a separate PR …
=> tools/CI: scan repository with trivy security scanner (yarn.lock, composer.lock)

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.43.1
=> tools/Makefile: update trivy to v0.43.1

plugins/pubsubhubbub/README.md
Clarify old and new name along with Wikipedia link.
=> Doc update, WebSub (formerly PubSubHubbub) plugin

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.44.0
=> tools/tests: update trivy to v0.44.0

doc/md/Community-and-related-software.md, doc/md/Plugins.md, doc/md/REST-API.md, doc/md/Reverse-proxy.md, doc/md/Server-configuration.md, doc/md/Shaarli-configuration.md, doc/md/dev/Development.md, doc/md/dev/GnuPG-signature.md, doc/md/dev/Theming.md, doc/md/dev/Translations.md, doc/md/index.md
Stumbled across this while building the docs using mkdocs 1.5.2, following readthedocs' email `Make sure your project is compatible with MkDocs >= 1.x` from 2023/08/02
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/live/GIT/Shaarli/doc/html
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'Usage#tag-cloud', it was left
as is. Did you mean 'Usage.md#tag-cloud'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'Usage#picture-wall', it was
left as is. Did you mean 'Usage.md#picture-wall'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'Usage#import-export', it was
left as is. Did you mean 'Usage.md#import-export'?
INFO    -  Doc file 'Community-and-related-software.md' contains an …
```
=> doc: fix mkdocs build warnings/relative links

doc/md/Community-and-related-software.md
- fixes https://github.com/shaarli/shaarli-pkg-debian/issues/8
- https://github.com/shaarli/shaarli-pkg-debian is unmaintained, please use downstream packaging repo at https://salsa.debian.org/php-team/pear/shaarli
- https://github.com/shaarli/shaarli-pkg-debian will be archived after this PR is merged
=> doc: community/related software/integration with other platforms: add link to shaarli debian package

doc/md/Server-configuration.md
- Tested with php-fpm 8.2.7-1~deb12u1 on Debian 12
- ref. https://github.com/shaarli/Shaarli/issues/2020
=> doc: server configuration: add PHP 8.2 to PHP compatibility table

Dockerfile
- the previous (0.12.2) release image was based on 3.16.4 since the .patch version was not specified, which shows vulnerabilities when scanned with trivy (https://github.com/shaarli/Shaarli/pull/2019)
=> docker: update base alpine docker image to 3.16.7

application/front/controller/visitor/BookmarkListController.php
It affects the title tag of the bookmark list page. 
Fixes shaarli/Shaarli#2038
=> Fix XSS vulnerability in tag search

application/Utils.php, application/front/controller/visitor/FeedController.php, application/http/HttpUtils.php, index.php, tests/languages/de/UtilsDeTest.php, tests/languages/en/UtilsEnTest.php, tests/languages/fr/UtilsFrTest.php
PHP 8.2.13 and 8.1.26 introduced another error preventing the CI to pass with default POSIX locale. We now have a wrapper to get the locale and replace C with a valid locale.
@see https://github.com/php/php-src/issues/12561
Fixes #2029
=> PHP 8.x intl incompatibility: failback C locale with en_US

.github/workflows/docker-latest.yml, .github/workflows/docker-tags.yml
- only push the docker image to the ghcr registry when on the original shaarli/Shaarli fork
- only run trivy docker image scans on the original shaarli/Shaarli fork
- prevents 'Username and password required' errors when committing to forks which do not have the required CI secrets (registry username/password) set
=> github actions: don't attempt to push docker image from forks

tpl/default/tools.html
https://shaarli.readthedocs.io/en/master/Community-and-related-software/ ends on a 404 error page.
=> Documentation: fix broken link to 3rd party plugins

yarn.lock
- ref. https://github.com/shaarli/Shaarli/issues/2052
- manually tested locally with no signs of breakage or errors in the console
- fixes part of the warnings in the issue above, with only these warnings remaining:
```
yarn.lock (yarn)
================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 1, CRITICAL: 0)
┌─────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────┐
│   Library   │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                         Title                         │
├─────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────┤
│ glob-parent │ CVE-2020-28469 │ HIGH     │ …
```
=> frontend: update npm dependencies (npm audit fix)

doc/md/Troubleshooting.md
- ref. https://github.com/shaarli/Shaarli/pull/2037
- ref. https://github.com/shaarli/Shaarli/issues/531
=> doc: troubleshooting: list more cases in which title retrieval fails

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.47.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.48.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.48.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.48.2
- https://github.com/aquasecurity/trivy/releases/tag/v0.48.3
- https://github.com/aquasecurity/trivy/releases/tag/v0.49.0
=> tools: update trivy security scanner to v0.49.0

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.49.1
=> tools: update trivy security scanner to v0.49.1

doc/md/Server-configuration.md
Some themes (e.g. https://github.com/RolandTi/shaarli-stack) use SVG assets for example to provide the favicon. The web server configuration example provided in Shaarli's documentation does not allow accessing `.svg` files (a HTTP 403 error is returned). 
This Pull Request fixes it by allowing access to `.svg` files in the example configuration for Apache and Nginx.
Even though no SVG files are used in the default template, I think there are no real security concerns allowing them by default. The alternative is to mention in the documentation of those themes, that the virtualhost configuration file should be edited (not very user-friendly)
/cc @rolandTi
=> doc: server configuration: allow accessing and caching SVG assets

application/http/MetadataRetriever.php
Added `mb_convert_encoding()` on `$description` + `$tags`, like `$title`
=> Fix description retrieval when page charset is not UTF-8

Dockerfile
- https://alpinelinux.org/posts/Alpine-3.16.9-3.17.7-3.18.6-released.html
=> dockerfile: update base alpine linux docker image to v3.18.6

doc/md/Troubleshooting.md
- fixes https://github.com/shaarli/Shaarli/issues/2032
=> doc: troubleshooting: add solution for Allowed memory size of xxx bytes exhausted

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.50.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.50.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.50.2
- https://github.com/aquasecurity/trivy/releases/tag/v0.50.4
- https://github.com/aquasecurity/trivy/releases/tag/v0.51.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.51.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.51.2
=> tools/tests: update trivy security scanner to v0.51.2

Dockerfile, doc/md/dev/Development.md, tests/docker/alpine319/Dockerfile
- https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html
- https://www.alpinelinux.org/posts/Alpine-3.19.1-released.html
- https://www.alpinelinux.org/posts/Alpine-3.17.8-3.18.7-3.19.2-released.html
- https://www.alpinelinux.org/posts/Alpine-3.17.9-3.18.8-3.19.3-released.html
- https://alpinelinux.org/posts/Alpine-3.17.10-3.18.9-3.19.4-3.20.3-released.html
=> docker: update base alpine linux image to v3.19.4

Makefile
- https://github.com/aquasecurity/trivy/releases/tag/v0.51.4
- https://github.com/aquasecurity/trivy/releases/tag/v0.52.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.52.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.52.2
- https://github.com/aquasecurity/trivy/releases/tag/v0.53.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.54.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.54.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.55.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.55.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.55.2
- https://github.com/aquasecurity/trivy/releases/tag/v0.56.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.56.1
- https://github.com/aquasecurity/trivy/releases/tag/v0.56.2
=> tools/tests: update trivy vulnerability scanner to v0.56.2

Dockerfile
=> fix wrong date format when language is not english (Alpine icu package split)

application/bookmark/Bookmark.php, tests/bookmark/BookmarkTest.php, tests/front/controller/admin/ManageTagControllerTest.php
#2084 - If a bookmark already includes the tag that the old tag is being renamed to, effectively merge the tags by removing the old and keeping the new. Previously, the new tag would be duplicated.
=> 2084: Ensure tags are unique when renaming

package.json, yarn.lock
- micromatch: fixes https://avd.aquasec.com/nvd/2024/cve-2024-4067/
- webpack: fixes https://avd.aquasec.com/nvd/cve-2024-43788
- rm yarn.lock && yarnpkg install
- fixes https://github.com/shaarli/Shaarli/issues/2052
=> dependencies: update npm dependencies (npm audit fix)

CHANGELOG.md
- horizontal line between releases
- standardize blank lines before/after headings
=> doc: changelog: minor style tweaks/standardization/spacing

doc/md/Community-and-related-software.md
From a discussion in issue https://github.com/shaarli/Shaarli/discussions/2095 here are my plugins (one to display colors inline and the other to fill in metadata for youtube videos) and the template/theme I use.
=> Community: Added colorscheme and youtube plugins, and shirley-template

.github/act/Dockerfile, .github/workflows/ci.yml, Makefile, composer.json, composer.lock, tests/languages/en/UtilsEnTest.php
Updated the Github CI to use Ubuntu 24.04 correctly. The translation tests needed the $LANG environmental variable set and and the date regular expressions needed the /u UTF-8 flag. I also included PHP 8.3 and 8.4 and remove 7.4 and 8.0.
=> tests: fix CI and translation tests

application/front/controller/visitor/ShaarliVisitorController.php, tpl/default/linklist.html, tpl/vintage/page.header.html
I guess the title is self explanatory.
IMHO, this value should not be seen for public, unless this is an open instance and therefore, no logged is kind of already logged in.
=> Keep private links number … private.

.github/workflows/ci.yml
```
E: Repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu noble InRelease' changed its 'Label' value from '***** The main PPA for supported PHP versions with many PECL extensions *****' to 'PPA for PHP'
```
=> github actions: workaround for ondrej/php apt repository update error

.github/workflows/ci.yml, .github/workflows/docker-latest.yml, .github/workflows/docker-pr.yml, .github/workflows/docker-tags.yml, .github/workflows/trivy-release.yml
- https://github.com/shaarli/Shaarli/issues/2137
=> github actions: pin all base images to ubuntu-24.04
